### ISSUE TITLE
PVCs cannot be (guaranteed) safely be re-used between different NodeSpecs

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#1027] opened 2019-06-08 10:42 UTC
Each node spec may contain different scheduling options through `podTemplate`, and `PVC` created for them may be tied to a specific availability zone or even a single host.

It seems reasonably safe to re-use within a NodeConfig because they would have been successfully scheduled together at least once, e.g via `waitForFirstConsumer` or similar mechanisms.

**Comment by nkvoll** [comment] 2019-06-08 10:44
This would have been a lot easier to ensure if we made `name` a required attribute on the `NodeSpec`, wdyt @sebgl? Right now we only have indices, which is difficult to consider as "stable".

If we used a node name as the differentiator, we would additionally need a facility to specify which node specs a volume may be used in (this could be as simple as a well known label)?

**Comment by sebgl** [comment] 2019-07-17 08:22
With https://github.com/elastic/cloud-on-k8s/issues/1173, PVC reuse will (by design) be tied to a single named `NodeSpec`, as suggested by @nkvoll here.
I think we can close this issue.

**Closed by sebgl** 2019-07-17 08:22 UTC
