### ISSUE TITLE
Feature - support increasing data storage on existing nodes

### ISSUE THREAD

**Issue by wadeholler** [elastic/cloud-on-k8s#2604] opened 2020-02-24 14:12 UTC
## Proposal

Support increasing size of data storage.

**Use case. Why is this important?**
The cluster ran out of storage because we didn't think it would grow that much.  We tried to increase it by changing the data nodes storage size in their volume claim template.

**Environment**

* ECK version:

1.0.1

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ?
	* Cloud: AWS - self deployed
	* Kubernetes distribution: Upstream ?
	
	for each of them please give us the version you are using
```
$ kubectl version
```

* Resource definition:
```
if relevant insert the resource definition
```

* Logs:
```
insert operator logs or any relevant message to the issue here
```

**Comment by sebgl** [comment] 2020-02-24 14:22
This is indeed a limitation. The current workaround is to [rename the NodeSet with an increased storage requirement](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-orchestration.html#k8s-orchestration-limitations). As a result, ECK will create new Pods (with new storage reqs), migrate data from the old Pods to the new ones, then delete the old Pods. This should happen with no downtime nor data loss.

I'm closing since this is a duplicate of https://github.com/elastic/cloud-on-k8s/issues/325.

**Closed by sebgl** 2020-02-24 14:22 UTC

**Comment by sebgl** [comment] 2020-02-24 14:27
I updated the first post of https://github.com/elastic/cloud-on-k8s/issues/325 with a clearer explanation of the workaround.
