### ISSUE TITLE
problem deploying eck-stack using charts with logstash enabled and piplinerefs

### ISSUE THREAD

**Issue by ghaythta** [elastic/cloud-on-k8s#8143] opened 2024-10-22 12:22 UTC
the problem lies when you want to deploy logstash next to elastic like this:

..... elastic values here...

eck-logstash:
  enabled: true
  version: 8.15.3
  count: 1
  elasticsearchRefs:
    - name: elasticsearch
      clusterName: eck
  pipelinesRef:
    secretName: "logstash-pipeline-secret"
  services:
    - name: beats
      service:
        spec:
          type: LoadBalancer
          ports:
            - port: 5044
              name: "beats"
              protocol: TCP
              targetPort: 5044
    - name: tcp
      service:
        spec:
          type: LoadBalancer
          ports:
            - port: 50000
              name: "tcp"
              protocol: TCP
              targetPort: 50000

------

this will result in conflict and it will refuse to deploy saying that piplines and piplinesref cant be together at the same time

in my example it isnt

but because the way that values file for the nested logstash chart , it seems that it only overrides available values like the pipleinsref i have

and because pipline:[] is in the default values file , it will make the conflict

a fast fix is to download the charts locally and comment out the piplines:[] line in the nested logstah chart

**Comment by thbkrkr** [comment] 2024-10-22 13:00
It appears to be a duplicate of #8000, which has already been resolved via #8087.
The fix will be included in the upcoming ECK release (v2.15.0).

**Closed by thbkrkr** 2024-10-22 13:00 UTC
Labels: triage
