### ISSUE TITLE
Patching of v1beta1 ES resource with v1 on k8s 1.12 fails

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#2308] opened 2019-12-19 14:48 UTC
k8s 1.12 running ECK `1.0.0-rc3` upgraded from `v1beta1`

When upgrading what was created in `v1beta1` as 
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: es-apm-sample
spec:
  version: 7.4.0
  nodeSets:
    - name: default
      count: 3
      config:
        # This setting could have performance implications for production clusters.
        # See: https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-virtual-memory.html
        node.store.allow_mmap: false
```

with 
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-apm-sample
spec:
  version: 7.5.0
  nodeSets:
    - name: default
      count: 3
      config:
        # This setting could have performance implications for production clusters.
        # See: https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-virtual-memory.html
        node.store.allow_mmap: false
```

I run into the following error:

```
Error from server (InternalError): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"elasticsearch.k8s.elastic.co/v1\",\"kind\":\"Elasticsearch\",\"metadata\":{\"annotations\":{},\"name\":\"es-apm-sample\",\"namespace\":\"default\"},\"spec\":{\"nodeSets\":[{\"config\":{\"node.store.allow_mmap\":false},\"count\":3,\"name\":\"default\"}],\"version\":\"7.5.0\"}}\n"}},"spec":{"nodeSets":[{"config":{"node.store.allow_mmap":false},"count":3,"name":"default"}],"version":"7.5.0"}}
to:
Resource: "elasticsearch.k8s.elastic.co/v1, Resource=elasticsearches", GroupVersionKind: "elasticsearch.k8s.elastic.co/v1, Kind=Elasticsearch"
Name: "es-apm-sample", Namespace: "default"
Object: &{map["apiVersion":"elasticsearch.k8s.elastic.co/v1" "kind":"Elasticsearch" "metadata":map["annotations":map["common.k8s.elastic.co/controller-version":"1.0.0-beta1" "elasticsearch.k8s.elastic.co/cluster-uuid":"3S6znhdkQqK72AXerue8ow" "kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"elasticsearch.k8s.elastic.co/v1beta1\",\"kind\":\"Elasticsearch\",\"metadata\":{\"annotations\":{},\"name\":\"es-apm-sample\",\"namespace\":\"default\"},\"spec\":{\"nodeSets\":[{\"config\":{\"node.store.allow_mmap\":false},\"count\":3,\"name\":\"default\"}],\"version\":\"7.4.0\"}}\n"] "creationTimestamp":"2019-12-19T14:19:20Z" "finalizers":["finalizer.elasticsearch.k8s.elastic.co/observer" "finalizer.elasticsearch.k8s.elastic.co/secure-settings-secret" "finalizer.elasticsearch.k8s.elastic.co/http-certificates-secret"] "generation":'\x02' "name":"es-apm-sample" "namespace":"default" "resourceVersion":"6295" "selfLink":"/apis/elasticsearch.k8s.elastic.co/v1/namespaces/default/elasticsearches/es-apm-sample" "uid":"8c7defe8-226a-11ea-a356-42010a8e00ac"] "spec":map["http":map["service":map["metadata":map["creationTimestamp":<nil>] "spec":map[]] "tls":map["certificate":map[]]] "nodeSets":[map["config":map["node.store.allow_mmap":%!q(bool=false)] "count":'\x03' "name":"default" "podTemplate":map["metadata":map["creationTimestamp":<nil>] "spec":map["containers":<nil>]]]] "updateStrategy":map["changeBudget":map[]] "version":"7.4.0"] "status":map["availableNodes":'\x03' "health":"green" "phase":"Ready"]]}
for: "https://gist.githubusercontent.com/barkbay/f42682b17a41a9aca4c041c218d7b631/raw/477a4b4e73bc47d7c3b99b4d2c7b0121c6096ff0/03-update-v1beta1-with-v1.yml": Internal error occurred: no kind "Elasticsearch" is registered for version "elasticsearch.k8s.elastic.co/v1" in scheme "k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go:51"
```

**Comment by pebrc** [comment] 2019-12-19 14:54
Going back to `v1beta1` for that particular cluster works. Also it seems once one resource update has been made to that cluster with the code from version 1.0.0 subsequent updates work even when using `v1`

So this is IMO not a blocker.

**Comment by pebrc** [comment] 2019-12-19 16:33
Retested and it is not a caching issue. Does not go away even after 30 mins.

**Comment by barkbay** [comment] 2019-12-31 12:02
I got the same issue on EKS 1.12

**Comment by barkbay** [comment] 2019-12-31 12:22
I reverted the version to `v1beta1` with kubectl and it seems to unlock the situation, not sure to understand why.

Also it only affects `Elasticsearch`, not `Kibana` nor the `APMServer`

**Comment by barkbay** [comment] 2019-12-31 13:29
Likely caused by https://github.com/kubernetes/kubernetes/issues/73752, removing the webhook solves the issue.

Fix has been back-ported to `1.13`: https://github.com/kubernetes/kubernetes/pull/79495 but not to `1.12`

**Comment by barkbay** [comment] 2020-01-02 09:59
I was wondering why I didn't get the issue on OpenShift 3.11. I did some additional tests and just discovered that ... `ValidatingAdmissionWebhook` are not enabled by default in the API Server of OpenShift 3.11 :confused:

Once enabled I get the exact same issue.

**Comment by barkbay** [comment] 2020-01-03 07:58
> I reverted the version to v1beta1 with kubectl and it seems to unlock the situation

Here is a "one liner" to apply the aforementioned workaround on all the Elasticsearch resources in a cluster:

```bash
for ns in `kubectl get ns --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}'`; do \
for es in `kubectl get elasticsearch.elasticsearch.k8s.elastic.co --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}' -n ${ns}`; do \
kubectl get elasticsearch.elasticsearch.k8s.elastic.co/${es} -n ${ns} -o yaml | \
  sed -E 's/apiVersion: elasticsearch.k8s.elastic.co\/v1/apiVersion: elasticsearch.k8s.elastic.co\/v1beta1/' | \
  kubectl apply --validate=false -f -
 done
done
```

`kubectl patch` can't be used because it does some validation on the client side that prevents the patch to be applied.

**Comment by barkbay** [comment] 2020-01-03 12:56
Sum up of the different options that have been discussed offline:

* Since the issue is happening on K8S < 1.13 _(incl. OpenShift 3.11)_ while some `v1beta1` resources are deployed we can exclude these versions from the upgrade process. We could document that if a user has deployed previous Elasticsearch resources then these resources must be deleted before upgrading if they are running on an impacted K8S version.

* Provide a second installation manifest without the webhook.

* Document a workaround, either by applying [this command](https://github.com/elastic/cloud-on-k8s/issues/2308#issuecomment-570495017) or by requesting the user to delete manually the webhook.

In any case we should document that once ECK has been upgraded to 1.0 on K8S < 1.13 only `v1` resources must be deployed.

cc @agup006

**Comment by agup006** [comment] 2020-01-06 15:39
Looking at the workaround I'm worried some folks will run into unforseen issues, or find it problematic to run the script on OpenShift 3.11 and K8s 1.13. As we still have some flexibility going from beta -> GA the cleaner option is to tell folks from that platform to uninstall and reinstall the operator.

**Comment by barkbay** [comment] 2020-01-07 07:16
Superseded by #2357

**Closed by barkbay** 2020-01-07 07:16 UTC
Labels: >bug

**Comment by iahmad-khan** [comment] 2020-02-02 09:50
Same issue after upgrading the operator

**Comment by agup006** [comment] 2020-02-03 06:06
@iahmad-khan , did you uninstall or reinstall the operator going from beta to GA?
