### ISSUE TITLE
Investigate why ES startup time seems a bit slow

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#735] opened 2019-05-06 08:09 UTC
It looks like starting an ES node is pretty slow (1-2 minutes). 
Is it because of:
- our init containers?
- out process manager startup?
- something in the network
- cpu limitations?

We should investigate (and measure the exact time).

**Comment by thbkrkr** [comment] 2019-06-05 15:31
Small note: I realized recently that we spend _some time_ (20s-30s) before the readiness probe succeeds. Once ES is started, we are waiting for 3 successes with a 10 seconds period:
https://github.com/elastic/cloud-on-k8s/blob/52695895e4b60a9e664093c782af53a71982415d/operators/pkg/controller/elasticsearch/pod/readiness_probe.go#L11-L17

**Comment by barkbay** [comment] 2019-06-07 09:21
@thbkrkr yes,  I spotted that one as well

Here are some statistics with PR #1014:

### System information
- OS: Container-Optimized OS from Google - Linux 4.14.119+
- CRI: docker://17.3.2
- Kubelet: v1.11.10-gke.4
### Allocated resources (each Pod)
- CPU: 2
- Memory: 2Gi
- No PV

### Detailed start time of containers
|  |elasticsearch-sample-es-5bhbthwcrd|elasticsearch-sample-es-6vqnjp6klx|elasticsearch-sample-es-zpvzk599bk|
|-----|-----|-----|-----|
Transition to PodScheduled|08:59:35|08:59:35|08:59:35|
Start time of tweak-os-settings|08:59:36|08:59:36|08:59:36|
Start time of prepare-fs|08:59:37|08:59:37|08:59:38|
Start time of inject-process-manager|08:59:48|08:59:46|08:59:47|
Transition to Initialized|08:59:49|08:59:46|08:59:47|
Process manager starting|08:59:49|08:59:47|08:59:48|
ES Started (in log)|09:00:07|09:00:04|09:00:04|
Transition to Ready|09:00:08|09:00:05|09:00:09|
PodScheduled to Ready (s)|33.0|30.0|34.0|

**Comment by barkbay** [comment] 2019-06-07 09:31
Same statistics with only 1 CPU per ES node: 

### System information
- OS: Container-Optimized OS from Google - Linux 4.14.119+
- CRI: docker://17.3.2
- Kubelet: v1.11.10-gke.4
### Allocated resources to each Pod
- CPU: 1
- Memory: 2Gi
- No PV

### Detailed start time of containers
|  |elasticsearch-sample-es-25xkldmz5x|elasticsearch-sample-es-2g4w64d4m6|elasticsearch-sample-es-b7kfxmzclw|
|-----|-----|-----|-----|
Transition to PodScheduled|09:27:20|09:27:21|09:27:21|
Start time of tweak-os-settings|09:27:22|09:27:22|09:27:22|
Start time of prepare-fs|09:27:23|09:27:23|09:27:23|
Start time of inject-process-manager|09:27:41|09:27:39|09:27:42|
Transition to Initialized|09:27:41|09:27:39|09:27:42|
Process manager starting|09:27:42|09:27:40|09:27:43|
ES Started (in log)|09:28:12|09:28:12|09:28:18|
Transition to Ready|09:28:14|09:28:16|09:28:20|
PodScheduled to Ready (s)|54.0|55.0|59.0|

Note that:
- The images are pre-loaded on the server
- The 3 pods are running on 3 different zones

**Comment by nkvoll** [comment] 2019-06-08 16:10
Plugin installation are soon gone as a startup-requirement as well, so that should save around 9+ seconds on non-constrained (>= 2CPU on GKE) nodes according to my unscientific records.

It looks like we should be able to find great savings between PM starting and ES starting as well? Unless it's actually just the JVM-startup time that we're seeing (thus explaining the time difference between PM and ES startup)

**Comment by barkbay** [comment] 2019-06-10 07:53
![image](https://user-images.githubusercontent.com/976373/59179809-7ad03780-8b63-11e9-9d15-731577d7a75b.png)

- 80% of the time spent before the start of the process manager is about downloading and installing plugins
- The remaining time (between the red and the blue line) is JMV/ES startup.

Regarding plugin installation some improvements are discussed in #620 and #35.

**Comment by barkbay** [comment] 2019-06-18 08:44
I did another run with the following notable changes:
- Pods use a dynamically provisioned pvc. This induces a longer startup time between the scheduled event and the first init container start because the volume needs to be created and attached.
- Plugins are not installed anymore

![image](https://user-images.githubusercontent.com/976373/59666714-abdce780-91b5-11e9-9734-a7521c4e24b3.png)

**Comment by pebrc** [comment] 2019-06-18 13:16
@barkbay interesting! Can you share the tooling you used to create those numbers please, so that your research becomes reproducible

**Comment by barkbay** [comment] 2019-06-24 13:52
@pebrc, let me do some clean up and I'll do that :)

To sum up, with the latest changes and improvements, for a cluster with CPU >= 2 nodes:

- ~ 15 seconds spent in PV provisioning
- ~ 5 seconds spent in init. containers
- ~ 16 seconds in Elasticsearch startup

That seems to me to be descent figures.
@bleskes please let me know if you think we should spend more time on this.

Thank you

**Comment by barkbay** [comment] 2019-09-23 16:32
Closing for now, please reopen if more discussion is needed.

**Closed by barkbay** 2019-09-23 16:32 UTC
Labels: discuss
