### ISSUE TITLE
Elastic Maps Server doesn't recognise enterprise license

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#5251] opened 2022-01-17 06:12 UTC
ElasticMapsServer has issues with recognising license correctly starting in version `7.17.0-SNAPSHOT`:

`/api/status` returns:
```
{
  "version": "7.17.0",
  "overall": {
    "level": 3,
    "state": "critical",
    "title": "[1] services are critical",
    "message": "See the individual statuses for more information"
  },
  "services": {
    "License": {
      "level": 3,
      "state": "critical",
      "title": "License error",
      "message": "License [basic] for cluster [test-ems-tls-disabled-4vz9] not valid"
    },
    "Basemaps": {
      "level": 0,
      "state": "available",
      "title": "Success",
      "message": "Map resolution is limited to zoom level 8. If you require higher resolution basemaps, please follow the instructions to download and install tile service databases.",
      "meta": {
        "maxzoom": 8,
        "size": 381292544,
        "versionTile": "v3.12.2"
      }
    },
    "Boundaries": {
      "level": 0,
      "state": "available",
      "title": "Success",
      "meta": {
        "versions": [
          "v1",
          "v2",
          "v6.6",
          "v7.0",
          "v7.10",
          "v7.11",
          "v7.12",
          "v7.13",
          "v7.14",
          "v7.15",
          "v7.16",
          "v7.2",
          "v7.6",
          "v7.7",
          "v7.8",
          "v7.9",
          "v8.0",
          "v8.1",
          "v8.2",
          "v8.3",
          "v8.4",
          "v8.5",
          "v8.6",
          "v8.7"
        ],
        "size": 93497815
      }
    }
  }
}
```

while ECK has the enterprise license enabled:
```
$ k describe cm -n elastic-system elastic-licensing
Name:         elastic-licensing
Namespace:    elastic-system
Labels:       common.k8s.elastic.co/type=elastic-usage
Annotations:  <none>
Data
====
eck_license_level:
----
enterprise
```

This doesn't repro in the same test on `7.16.2`.

**Comment by pebrc** [comment] 2022-01-17 08:09
Do you have a link to the failed test in CI?

**Comment by david-kow** [comment] 2022-01-17 08:55
> Do you have a link to the failed test in CI?

Yes, should have included it in the original description: https://devops-ci.elastic.co/job/cloud-on-k8s-pr-full/99/testReport/junit/github/com_elastic_cloud-on-k8s_test_e2e_ems/TestElasticMapsServerVersionUpgradeToLatest8x_Elastic_Maps_Server_should_respond_to_requests/

**Comment by pebrc** [comment] 2022-01-17 12:33
As mentioned on the PR that surfaced this issue. The problem here is not Elastic Maps Server. The problem is that we are testing an upgrade from 7.16.2 to 8.0.0-SNAPSHOT with a production license. That's fine one the 7.16.2 side of the upgrade test as this a production build. As soon as we update to 8.0.0-SNAPSHOT however Elasticsearch is running on a Basic license because the development build--correctly--rejects the production license and reverts to Basic. I think these tests should not run in this upgrade path.

**Comment by pebrc** [comment] 2022-01-17 12:47
```
"docker.elastic.co/elastic-maps-service/elastic-maps-server-ubi8:7.16.2"
"docker.elastic.co/elastic-maps-service/elastic-maps-server-ubi8:7.16.2"
"docker.elastic.co/elasticsearch/elasticsearch:8.0.0-SNAPSHOT"
```
Versions according to our diagnostics in this test. The odd thing here is that I would expect the Elasticsearch version to be 7.16.2 and not 8.0.0-SNAPSHOT according to https://github.com/elastic/cloud-on-k8s/pull/4961/files#diff-43849638e1817d44d10d67bc2bf8555c54a026c77e3d8f9f5b7c0c9b153f62b4R103

**Comment by pebrc** [comment] 2022-01-17 13:44
> The odd thing here is that I would expect the Elasticsearch version to be 7.16.2 and not 8.0.0-SNAPSHOT

The test run was using a previous version of the code. I am tempted to close this issue. There is a discussion to be had around our practice of upgrade testing. Especially for EMS where we rely on upgrading EMS first before Elasticsearch to sidestep the issues highlighted here, which is in violation of the recommended upgrade order. The argument in favour of the current practice is that it EMS 'only' need Elasticsearch for license related functionality and saved us from setting up a dedicated test pipeline.

**Closed by pebrc** 2022-01-17 13:44 UTC
Labels: >bug, v2.0.0
