### ISSUE TITLE
Require authentication for process-manager

### ISSUE THREAD

**Issue by jordansissel** [elastic/cloud-on-k8s#927] opened 2019-05-23 22:34 UTC
## Proposal

The process-manager should require authentication. The credentials should be managed by the operator.

I was glancing around the [process-manager http code](https://github.com/elastic/cloud-on-k8s/blob/master/operators/pkg/controller/elasticsearch/processmanager/server.go#L35-L70) and noticed that TLS is supported (and on by default, it seems? Nice!), authentication is not required.

This will allow other things within the k8s cluster to use the process-manager endpoints. It is also possible to expose this externally if one makes a mistake creating a misconfigured service/load balancer, etc.

Example:

```
% kubectl run jls-test2 -it --image centos:7 bash
...
[root@jls-test2-7cc7cd4bb8-shct4 /]# curl -k https://10.20.2.2:8080/es/status; echo
{"state":"started","since":"17m39.965338848s","config_checksum":"2816413477"}
```

The above is a separate pod hitting `/es/status` endpoint on one of my Elasticsearch pods deployed with cloud-on-k8s.

There are a number of possibly sensitive endpoints in the process-manager (`/es/stop`, etc) which would benefit from some additional protection.

**Comment by sebgl** [comment] 2019-05-24 07:27
Looks like a duplicate of https://github.com/elastic/cloud-on-k8s/issues/731, we intend to support this by verifying the client certificate from the process-manager server.
Let's close this one and leave #731 open.

@jordansissel please reopen if you think it should be handled differently :)

**Closed by sebgl** 2019-05-24 07:27 UTC
