### ISSUE TITLE
Volume permission errors when running Enterprise Search on OCP (E2E)

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#3274] opened 2020-06-17 08:57 UTC
`TestSamples/enterprisesearch-ent_es/Enterprise_Search_Pods_should_eventually_be_read` is failing consistantly since being introduced (all runs between [140](https://devops-ci.elastic.co/view/cloud-on-k8s/job/cloud-on-k8s-e2e-tests-ocp/140/) and [144](https://devops-ci.elastic.co/view/cloud-on-k8s/job/cloud-on-k8s-e2e-tests-ocp/144/), but [142](https://devops-ci.elastic.co/view/cloud-on-k8s/job/cloud-on-k8s-e2e-tests-ocp/142/) which fails earlier).

**Comment by sebgl** [comment] 2020-06-17 09:21
```
"containerStatuses": [
                    {
                        "containerID": "cri-o://3b77c37c467897306840f57a2507f8e1be3a7f557256f4fd6cf12f35283cfe80",
                        "image": "docker.elastic.co/enterprise-search/enterprise-search:7.7.1",
                        "imageID": "docker.elastic.co/enterprise-search/enterprise-search@sha256:96a6484cc077576c1554cad1e537c3ed524634202e97478d617aca5bc0562a6d",
                        "lastState": {
                            "terminated": {
                                "containerID": "cri-o://3b77c37c467897306840f57a2507f8e1be3a7f557256f4fd6cf12f35283cfe80",
                                "exitCode": 1,
                                "finishedAt": "2020-06-17T01:12:01Z",
                                "reason": "Error",
                                "startedAt": "2020-06-17T01:12:01Z"
                            }
                        },
                        "name": "enterprise-search",
                        "ready": false,
                        "restartCount": 6,
                        "started": false,
                        "state": {
                            "waiting": {
                                "message": "back-off 5m0s restarting failed container=enterprise-search pod=ent-sample-j2bt-ent-9dbdbdc8b-tf9j9_e2e-qj18m-mercury(15453832-0fc8-4964-a45e-5476ee5a87b4)",
                                "reason": "CrashLoopBackOff"
                            }
                        }
                    }
```

**Comment by sebgl** [comment] 2020-06-17 10:06
Reproduced locally:

```
❯ k logs -p ent-sample-9v6s-ent-77cc976cd-szs25 -n e2e-mercury                                       
/usr/local/bin/docker-entrypoint.sh: line 24: /usr/share/enterprise-search/config/enterprise-search.yml: Permission denied
```

**Comment by sebgl** [comment] 2020-06-17 10:18
Openshift creates the Pod with:

```
"securityContext": {
            "fsGroup": 1000530000,
            "runAsNonRoot": true,
            "seLinuxOptions": {
                "level": "s0:c23,c12"
            }
        },
```

and `/usr/share/enterprise-search/config` belongs to the `enterprise-search` user:

```
bash-4.2$ ls -la /usr/share/enterprise-search/config
total 24
drwxr-xr-x 2 enterprise-search enterprise-search 4096 May 12 04:27 .
drwxr-xr-x 7 enterprise-search enterprise-search 4096 May 12 04:30 ..
-rw-r--r-- 1 enterprise-search enterprise-search 8650 May 12 04:27 enterprise-search.yml
-rw-r--r-- 1 enterprise-search enterprise-search  306 May 12 04:27 env.sh
```

It looks like `docker-entrytpoint.sh` attempts to overwrite the config file:

```
# Only override config file if it doesn't exist or it's all commented lines (the default).
# This is so if a user mounts their own config file, we will leave it alone
if [[ ! -f /usr/share/enterprise-search/config/enterprise-search.yml ]] || ! grep -q -v '^\s*#' /usr/share/enterprise-search/config/enterprise-search.yml; then
  printf '%s\n' "${as_opts[@]}" | sort > /usr/share/enterprise-search/config/enterprise-search.yml
fi
```

I think this could be resolved by mounting the config in `/usr/share/enterprise-search/config/enterprise-search.yml` instead of using our own custom path.

**Comment by sebgl** [comment] 2020-06-17 12:00
Next error after solving the configuration file permission problem:

```
Creating log directory: /usr/share/enterprise-search/logERROR: org.jruby.exceptions.SystemCallError: (EACCES) Permission denied - /usr/share/enterprise-search/log
org.jruby.exceptions.SystemCallError: (EACCES) Permission denied - /usr/share/enterprise-search/log
```

**Closed** 2020-06-23 07:52 UTC
Labels: >bug, >test
