### ISSUE TITLE
bug: elasticsearch filesystem init container fails and brings down whole cluster

### ISSUE THREAD

**Issue by mgorsk1** [elastic/cloud-on-k8s#5445] opened 2022-03-07 16:11 UTC
## Bug Report
**What did you do?**

- We have deployed **Elasticsearch 8.0.0** clusters on our acc and prod environments. 
- Each cluster is deployed in a separate namespace, we have 3 master and 3 (acc) / 4 (prod) data nodes in each installation. 
- We have implemented `topologySpreadConstraints` so each pod of master/node statefulset is on a different rack (we have 4 racks with k8s nodes).

**What did you see instead? Under which circumstances?**

Periodically we see whole clusters going down. The symptoms are - multiple pods are in `Init:CrashLoopBackOff` state (it happens at the same time for all of them) as per below screenshot.

![image](https://user-images.githubusercontent.com/5680655/157070913-b561dafd-12aa-4b85-96f5-8f25de63df1e.png)

When I delete a pod so it's recreated, the pod is in `Running` state (1/1) but fails to form a cluster - discovery process fails and whole cluster is basically unusable. This requires deleting Elastic cluster resource and deploying it from scratch. It never happened for ES version 6, it started after upgrading to version 7 and persists in version 8, which we hoped would solve this issue.

Failing container is named **elasticsearch-internal-init-filesystem** and the error says _cp: cannot create regular file /mnt/elastic-internal ..._ (see below for full screenshot)

We suspected it's due to deleting pods residing on the same rack but since we have implemented `topologySpreadConstraints` this hypothesis was rejected.

**Environment**

* ECK version: **1.6.0**

* Kubernetes information:

	- On premise kubernetes version: **1.20.11**
```
$ kubectl version
```

* Resource definition:

partial mount section of node statefulset:
![image](https://user-images.githubusercontent.com/5680655/157070364-3c999ea5-5ebf-4a7f-8bde-f1e7ee55ab5e.png)

* Logs:

logs from elasticsearch-internal-init-filesystem

![image](https://user-images.githubusercontent.com/5680655/157069947-77293a1c-bc6c-4769-80f8-036131459c7a.png)

**Comment by thbkrkr** [comment] 2022-03-08 10:59
Are you using a volume provisioner?
Are you using custom images?
How frequently does it happen per pod?
Is there something that could trigger an auto-restart of pods?

Root causes could be:
- The init container has been deleted (as in docker rm) by a garbage collection mechanism, and the kubelet attempted to restart the init container. This is the case described in https://github.com/kubernetes/kubernetes/issues/67261#issuecomment-414152720
- 2 versions of the same image have been deployed on the cluster and there was a permission issue with the first version preventing the init container to start
- more restrictive permissions/incorrect labelling on the `/var/lib/kubelet` directory

The first two were adressed starting ECK 1.9.0 (07 Dec 2021) by:
- https://github.com/elastic/cloud-on-k8s/issues/4877

I advise you to upgrade to the latest version of ECK (2.0.0).

> When I delete a pod so it's recreated, the pod is in Running state (1/1) but fails to form a cluster - discovery process fails and whole cluster is basically unusable.

This is odd. Typically deleting the pod should fix the issue because a fresh init container is created. The files are copied to an [emptyDir volume](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir). The lifecycle of this volume is tied to the Pod's lifecycle. An emptyDir volume exists as long as that Pod is running on that node. As the name says, the emptyDir volume is initially empty. if the Pod is deleted then a new Pod is initialized with a new, empty, volume.

Can you share the Elasticsearch log of the new container that has the discovery issues after the previous one entered in an Init:CrashLoopBackOff and you deleted it?

**Comment by mgorsk1** [comment] 2022-03-14 07:16
Thanks for replying @thbkrkr , indeed your instincts were not wrong. Turns out we have docker image pruning run on schedule on k8s nodes and it correlates with failures with Elasticsearch. We will upgrade to ECS 2.0 and see if that helps. Thanks!

**Comment by thbkrkr** [comment] 2022-03-17 10:16
> We will upgrade to ECK 2.0 and see if that helps.

It should, hence closing. Feel free to reopen if needed. Thanks.

**Closed by thbkrkr** 2022-03-17 10:16 UTC
Labels: >bug

**Comment by mgorsk1** [comment] 2022-03-17 11:08
It did, thanks.
