### ISSUE TITLE
Fleet agent never associates with kibana if basePath: /kibana  is defined operator

### ISSUE THREAD

**Issue by dadez73** [elastic/cloud-on-k8s#8170] opened 2024-10-31 15:30 UTC
We are using ECK with Elastic Agents Managed by Fleet and have installed the Kubernetes Integration.

I noticed that if i rewrite the url  basepath of kibana the operator still point to the default url that is without basepath. This block the fleet autonerollement , deployments that have kibanaRef: in config are not deployed as the operator cannot contact kibana.

Thank you!

Kibana config slice:

spec:
  config:
    monitoring:
      kibana.collection.enabled: true
      ui.ccs.enabled: false
    server:
      basePath: /kibana
      host: 0.0.0.0
      publicBaseUrl: https://XXXXXXX/kibana
      rewriteBasePath: true

{"name":"eck-fleet-server","namespace":"elk"},"namespace":"elk","name":"eck-fleet-server","reconcileID":"f0cec043-f512-46b5-b0d6-f13f0b0b7299","error":"failed to request http://kibana-kb-http.elk.svc:5601/api/fleet/enrollment_api_keys?perPage=20&page=1, status is 404)

**Comment by kvalliyurnatt** [comment] 2024-11-11 13:47
this seems like a duplicate of #7909  which should be fixed in the next release (2.15.0)

**Closed** 2024-11-11 14:33 UTC
Labels: triage
