### ISSUE TITLE
No diagnostic bundle on failed kind-k8s-versions e2e tests

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#2838] opened 2020-04-08 12:35 UTC
Example: https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-kind-k8s-versions/44/
Test failed but there seem to be no diagnostic bundle linked to the Jenkins job.

I guess there's something different in the k8s-versions vs. the stack-versions Jenkins job.

**Comment by thbkrkr** [comment] 2020-04-10 15:32
I have not yet managed to reproduce it locally, so I don't know where to look.

**Comment by thbkrkr** [comment] 2020-04-23 20:00
I think this happens when failure occurs during the deployment of the operator, filebeat or the test job before testing begins.
We dump the events log and run the diagnostic script only if there is a failure during the test job:
https://github.com/elastic/cloud-on-k8s/blob/bbdc6126f8d836a814a0856fc8da1fbf3dcfbc17/test/e2e/cmd/run/run.go#L70-L73
https://github.com/elastic/cloud-on-k8s/blob/bbdc6126f8d836a814a0856fc8da1fbf3dcfbc17/test/e2e/cmd/run/run.go#L270-L289

Unfortunately we no longer have the log of the execution 44 which made you open this issue to confirm this.

Example here: https://devops-ci.elastic.co/blue/organizations/jenkins/cloud-on-k8s-e2e-tests-kind-k8s-versions/detail/cloud-on-k8s-e2e-tests-kind-k8s-versions/62/pipeline
The test failed without diagnostic bundle.
```go
{"log.level":"info","@timestamp":"2020-04-20T13:35:08.307Z","message":"Waiting for pod to be ready","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","name":"eck-e2e-lx0tq-gh4kg","status":"Pending"}
{"log.level":"info","@timestamp":"2020-04-20T13:35:49.199Z","message":"Pod is in failed state","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","name":"eck-e2e-lx0tq-gh4kg"}
{"log.level":"info","@timestamp":"2020-04-20T13:35:49.199Z","message":"Cluster event log","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0"}
{"reason":"FailedMount","message":"MountVolume.SetUp failed for volume \"monitoring-ca\" : secret \"eck-e2e-lx0tq\" not found","kind":"Pod","name":"filebeat-d5zsf","namespace":"e2e-lx0tq"}
{"reason":"FailedCreate","message":"Error creating: pods \"filebeat-\" is forbidden: error looking up service account e2e-lx0tq/filebeat: serviceaccount \"filebeat\" not found","kind":"DaemonSet","name":"filebeat","namespace":"e2e-lx0tq"}
{"reason":"Failed","message":"Error: context deadline exceeded","kind":"Pod","name":"e2e-lx0tq-operator-0","namespace":"e2e-lx0tq-elastic-system"}
{"reason":"Failed","message":"Error: failed to reserve container name \"manager_e2e-lx0tq-operator-0_e2e-lx0tq-elastic-system_0d2221aa-02a1-45a4-a801-75c08e640508_0\": name \"manager_e2e-lx0tq-operator-0_e2e-lx0tq-elastic-system_0d2221aa-02a1-45a4-a801-75c08e640508_0\" is reserved for \"0c8e2231512e0b95c0d3359c77d95bc9aa701d61861efd0140be99349e516239\"","kind":"Pod","name":"e2e-lx0tq-operator-0","namespace":"e2e-lx0tq-elastic-system"}
{"reason":"Failed","message":"Error: context deadline exceeded","kind":"Pod","name":"eck-e2e-lx0tq-gh4kg","namespace":"e2e-lx0tq"}
{"log.level":"info","@timestamp":"2020-04-20T13:35:53.631Z","message":"Deleting resources","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","file":"/tmp/eck-e2e/e2e-lx0tq/config_e2e_batch_job.yaml"}
{"log.level":"info","@timestamp":"2020-04-20T13:36:36.460Z","message":"Cleaning up the scratch directory","service.version":"0.0.0-00000000","service.type":"eck","ecs.version":"1.4.0","directory":"/tmp/eck-e2e/e2e-lx0tq"}
Error: test run failed: tests failed
exit status 1
make[1]: *** [Makefile:389: e2e-run] Error 1
```

The '_failed to reserve container name_' error has already been seen (#2632).

We could change the code to run the diagnostic script at the first error. I'm not sure how it will be relevant but it does not cost much.

**Comment by thbkrkr** [comment] 2020-05-06 09:51
Closing because as explained below it's normal to not have a diagnostic bundle when the failure occurs during the deployment of the operator, filebeat or the test job before the E2E tests start with the error 'failed to reserve container name' (#2632).

**Closed by thbkrkr** 2020-05-06 09:51 UTC
Labels: :ci, >test
