### ISSUE TITLE
Could not resolve placeholder 'NODE_NAME'

### ISSUE THREAD

**Issue by Prodian0013** [elastic/cloud-on-k8s#3038] opened 2020-05-12 04:33 UTC
## Bug Report
**What did you do?**
Created 2 secrets in kubernetes then added secureSettings to the elastic deployment.
All elastic pods are in `Init CrashLoopBackoff`.  Elastic be dead.

**What did you expect to see?**
For the init keystore container to actually work using the secureSettings.

**What did you see instead? Under which circumstances?**
```
kubectl logs hulk-es-master-0 -c elastic-internal-init-keystore
Initializing keystore.
+ echo 'Initializing keystore.'
+ /usr/share/elasticsearch/bin/elasticsearch-keystore create
Exception in thread "main" java.lang.IllegalArgumentException: Could not resolve placeholder 'NODE_NAME'
	at org.elasticsearch.common.settings.PropertyPlaceholder.parseStringValue(PropertyPlaceholder.java:116)
	at org.elasticsearch.common.settings.PropertyPlaceholder.replacePlaceholders(PropertyPlaceholder.java:69)
	at org.elasticsearch.common.settings.Settings$Builder.replacePropertyPlaceholders(Settings.java:1162)
	at org.elasticsearch.common.settings.Settings$Builder.replacePropertyPlaceholders(Settings.java:1118)
	at org.elasticsearch.node.InternalSettingsPreparer.initializeSettings(InternalSettingsPreparer.java:108)
	at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:90)
	at org.elasticsearch.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:100)
	at org.elasticsearch.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:91)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:91)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.common.settings.KeyStoreCli.main(KeyStoreCli.java:41)
```

**Environment**

* ECK version:

	1.1.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ? Yes
```
Bare Metal
Red Hat Enterprise Linux Server release 7.8 (Maipo)
```	
	for each of them please give us the version you are using
```
$ kubectl version
```
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
if relevant insert the resource definition
```

* Logs:
```
insert operator logs or any relevant message to the issue here
```

**Comment by Prodian0013** [comment] 2020-05-12 05:19
Think I know the issue...

The elastic-internal-init-keystore container is reading the `elasticsearch-config from elastic-internal-elasticsearch-config` which has
```      
node.attr.node_name: ${NODE_NAME}
cluster.routing.allocation.awareness.attributes: node_name
```
And Im not able to add the additional env to the elastic-internal-init-keystore container
```
          env:          
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
```

**Comment by barkbay** [comment] 2020-05-12 06:44
You should be able to set the `NODE_NAME` in the init container variable with something along those lines:

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.6.0
  nodeSets:
    - name: default
      config:
       < insert your es config here >
      podTemplate:
        spec:
          initContainers:
             - name: elastic-internal-init-keystore # your init container
               env:
                 - name: NODE_NAME
                   valueFrom:
                     fieldRef:
                       fieldPath: spec.nodeName
               command:
                 - sh
                 - -c
                 - |
                   echo "${NODE_NAME}"
          containers:
            - name: elasticsearch
               [...]
```

**Comment by sebgl** [comment] 2020-05-12 07:49
Relates https://github.com/elastic/cloud-on-k8s/issues/2306 (it's currently not possible to easily override the init container spec).

**Comment by Prodian0013** [comment] 2020-05-12 13:07
> Relates #2306 (it's currently not possible to easily override the init container spec).
> I think the workaround right now is probably to copy-paste the entire content of the valid `elastic-internal-init-keystore` initContainer, and modify it with your own env var. Not ideal indeed.

Yeah it's not ideal.  If those internal init containers use the elasticsearch-config then it should also use the same envs as well.  Or at least allow a way to override the es config.

**Comment by charith-elastic** [comment] 2020-05-12 14:34
Since the root cause of this problem is already tracked by #2306, I am closing this issue. Until #2306 is addressed, the workaround is to copy the full definition of the `elastic-internal-init-keystore` init container into the manifest and copy over any extra environment variable definitions from the `elasticsearch` container as well. Something like the following:

```yaml
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: hulk
spec:
  version: 7.6.2
  secureSettings:
    - secretName: gcs-credentials
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
      node.attr.node_name: ${NODE_NAME}
      cluster.routing.allocation.awareness.attributes: node_name
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
            env: &common-env
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              - name: POD_IP
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: status.podIP
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
        initContainers:
          - name: install-plugins
            env: *common-env
            command:
              - sh
              - -c
              - |
                bin/elasticsearch-plugin install --batch repository-gcs
          - name: elastic-internal-init-keystore
            command:
              - /usr/bin/env
              - bash
              - -c
              - "#!/usr/bin/env bash\n\nset -eux\n\necho \"Initializing keystore.\"\n\n#
                create a keystore in the default data path\n/usr/share/elasticsearch/bin/elasticsearch-keystore
                create\n\n# add all existing secret entries into it\nfor filename in  /mnt/elastic-internal/secure-settings/*;
                do\n\t[[ -e \"$filename\" ]] || continue # glob does not match\n\tkey=$(basename
                \"$filename\")\n\techo \"Adding \"$key\" to the keystore.\"\n\t/usr/share/elasticsearch/bin/elasticsearch-keystore
                add-file \"$key\" \"$filename\"\ndone\n\necho \"Keystore initialization
                successful.\"\n"
            env: *common-env
            image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
            imagePullPolicy: IfNotPresent
            securityContext:
              privileged: false
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /mnt/elastic-internal/secure-settings
                name: elastic-internal-secure-settings
                readOnly: true
              - mountPath: /usr/share/elasticsearch/data
                name: elasticsearch-data
              - mountPath: /mnt/elastic-internal/downward-api
                name: downward-api
                readOnly: true
              - mountPath: /usr/share/elasticsearch/bin
                name: elastic-internal-elasticsearch-bin-local
              - mountPath: /mnt/elastic-internal/elasticsearch-config
                name: elastic-internal-elasticsearch-config
                readOnly: true
              - mountPath: /usr/share/elasticsearch/config
                name: elastic-internal-elasticsearch-config-local
              - mountPath: /usr/share/elasticsearch/plugins
                name: elastic-internal-elasticsearch-plugins-local
              - mountPath: /usr/share/elasticsearch/config/http-certs
                name: elastic-internal-http-certificates
                readOnly: true
              - mountPath: /mnt/elastic-internal/probe-user
                name: elastic-internal-probe-user
                readOnly: true
              - mountPath: /usr/share/elasticsearch/config/transport-remote-certs/
                name: elastic-internal-remote-certificate-authorities
                readOnly: true
              - mountPath: /mnt/elastic-internal/scripts
                name: elastic-internal-scripts
                readOnly: true
              - mountPath: /usr/share/elasticsearch/config/transport-certs
                name: elastic-internal-transport-certificates
                readOnly: true
              - mountPath: /mnt/elastic-internal/unicast-hosts
                name: elastic-internal-unicast-hosts
                readOnly: true
              - mountPath: /mnt/elastic-internal/xpack-file-realm
                name: elastic-internal-xpack-file-realm
                readOnly: true
              - mountPath: /usr/share/elasticsearch/logs
                name: elasticsearch-logs
```

**Closed by charith-elastic** 2020-05-12 14:34 UTC
Labels: >bug

**Comment by jketcham** [comment] 2022-04-02 00:20
I just ran into this problem when following the directions for [Topology spread constraints and availability zone awareness](https://github.com/elastic/cloud-on-k8s/blob/0d0df39cc1830044a378d79bc3693d60bb52a33b/docs/orchestrating-elastic-stack-applications/elasticsearch/advanced-node-scheduling.asciidoc#topology-spread-constraints-and-availability-zone-awareness) in the docs, where it instructs to add a `ZONE` env var to key off of for spreading nodes out across availability zones. 

The `ZONE` env var also needs to be added to the `elastic-internal-init-keystore` init container, and any other init containers added by the user (e.g. for installing plugins), or else it those will also fail in a crash loop.

Am I missing something where that should be taken care of, or should there be a new issue to add a note about that in the docs?

cc @charith-elastic
