### ISSUE TITLE
Ensure ECK is compatible with ipv6 (only) environments

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#3408] opened 2020-07-08 12:33 UTC
We should make sure ECK can run on k8s clusters with:

- [x] ipv4 only
- [x] ipv6 only (see #3649 for that)
- [ ] dual ipv4/ipv6

**Comment by shubhaat** [comment] 2020-07-09 03:22
What is the usecase for IPv6?

**Comment by Frankkkkk** [comment] 2020-08-20 12:32
In general, v6-listening on `::` will also accept IPv4 addresses (except on some, obscure, machines with IPv6 completely disabled).

This shall support the 3 above usecases

**Comment by pebrc** [comment] 2020-08-20 17:35
Let's start with verifying that ECK works in IPv6 environments with a smoke test in kind.

**Comment by pebrc** [comment] 2020-08-21 07:58
One thing we are already aware of is that IPv6 addresses need to be bracketed when used in resource identifiers. I believe this affects mostly ECK's rendering of configuration files where we use IP addresses for seed hosts and are currently not using brackets for for IPv6.

```
 ["java.lang.IllegalArgumentException: IPv6 addresses must be bracketed: fd00:10:244:0:3::9:9300"
```

**Comment by anyasabo** [comment] 2020-11-03 18:25
Closing this out as the original goal of the issue is complete, the remaining task is dual stack which can be a separate issue.

**Closed by anyasabo** 2020-11-03 18:25 UTC
Labels: >feature
