### ISSUE TITLE
ECK managed elasticsearch (with TLS enabled) getting flooded with "received plaintext http traffic on an https channel" logs

### ISSUE THREAD

**Issue by dobharweim** [elastic/cloud-on-k8s#6231] opened 2022-12-14 01:04 UTC
## Bug Report
**Versions:**
Openshift version: 4.10.39_1545
ECK Operator version 2.5.0
Elasticsearch version 8.5.3

**What did you do?**
1. [Install the operator](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-install-helm.html#k8s-install-helm-global) with the helm charts using all default values. `helm install elastic-operator elastic/eck-operator -n elastic-system --create-namespace`
2. [Install the quickstart guide](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-elasticsearch.html#k8s-deploy-elasticsearch) elasticsearch cluster in the `elastic-stack` namespace. 
```
cat <<EOF | kubectl apply -f -
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.5.3
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
EOF
```
3. Wait for the `quickstart-es-default-0` to be ready and running for about 5 minutes.
4. Check the logs of `quickstart-es-default-0`. `kubectl logs -f quickstart-es-default-0`.

**What did you expect to see?**
I expect to see ES running cleanly with no errors or connections coming in at this point.

**What did you see instead? Under which circumstances?**
I see the logs flooded with the following messages:
```
{"@timestamp":"2022-12-13T12:49:18.030Z", "log.level": "WARN", "message":"received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/[0:0:0:0:0:0:0:1]:9200, remoteAddress=/[0:0:0:0:0:0:0:1]:34354}", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[quickstart-es-default-0][transport_worker][T#5]","log.logger":"org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4HttpServerTransport","elasticsearch.cluster.uuid":"ndJIxxD-RkS-V_CLaP3ekQ","elasticsearch.node.id":"lkE7y6e-T7K0vH7X67aSPQ","elasticsearch.node.name":"quickstart-es-default-0","elasticsearch.cluster.name":"quickstart"}
{"@timestamp":"2022-12-13T12:49:18.032Z", "log.level": "WARN", "message":"received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/[0:0:0:0:0:0:0:1]:9200, remoteAddress=/[0:0:0:0:0:0:0:1]:34356}", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[quickstart-es-default-0][transport_worker][T#6]","log.logger":"org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4HttpServerTransport","elasticsearch.cluster.uuid":"ndJIxxD-RkS-V_CLaP3ekQ","elasticsearch.node.id":"lkE7y6e-T7K0vH7X67aSPQ","elasticsearch.node.name":"quickstart-es-default-0","elasticsearch.cluster.name":"quickstart"}
{"@timestamp":"2022-12-13T12:49:19.034Z", "log.level": "WARN", "message":"received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/[0:0:0:0:0:0:0:1]:9200, remoteAddress=/[0:0:0:0:0:0:0:1]:34370}", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[quickstart-es-default-0][transport_worker][T#7]","log.logger":"org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4HttpServerTransport","elasticsearch.cluster.uuid":"ndJIxxD-RkS-V_CLaP3ekQ","elasticsearch.node.id":"lkE7y6e-T7K0vH7X67aSPQ","elasticsearch.node.name":"quickstart-es-default-0","elasticsearch.cluster.name":"quickstart"}
{"@timestamp":"2022-12-13T12:49:19.037Z", "log.level": "WARN", "message":"received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/[0:0:0:0:0:0:0:1]:9200, remoteAddress=/[0:0:0:0:0:0:0:1]:34372}", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[quickstart-es-default-0][transport_worker][T#8]","log.logger":"org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4HttpServerTransport","elasticsearch.cluster.uuid":"ndJIxxD-RkS-V_CLaP3ekQ","elasticsearch.node.id":"lkE7y6e-T7K0vH7X67aSPQ","elasticsearch.node.name":"quickstart-es-default-0","elasticsearch.cluster.name":"quickstart"}
```
At this point there is nothing else running on the cluster, except for the quickstart ES pod and the operator.

**Environment**

* ECK version:

	2.5.0

* Kubernetes information:

	Running on IBM cloud with either OpenShift version: 4.10.39_1545 or IBM Cloud Kubernetes Service (IKS) 1.25.4 produces the same result.

OpenShift:
```
$ oc version
Client Version: 4.11.18
Kustomize Version: v4.5.4
Server Version: 4.10.39
Kubernetes Version: v1.23.12+7566c4d
```

IKS:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:28:30Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4+IKS", GitCommit:"e330c4230e5324d7206c1e2e588c67ba717cf496", GitTreeState:"clean", BuildDate:"2022-11-10T19:38:04Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**
[OpenShift operator logs](https://github.com/elastic/cloud-on-k8s/files/10223248/openshift_eck_logs.log)
[OpenShift ES pod logs](https://github.com/elastic/cloud-on-k8s/files/10223249/openshift_es_logs.log)
[IKS operator logs](https://github.com/elastic/cloud-on-k8s/files/10223250/elastic-operator-0.log)
[IKS ES pod logs](https://github.com/elastic/cloud-on-k8s/files/10223251/quickstart-es-default-0.log)

**Comment by barkbay** [comment] 2023-01-18 05:57
I ran the exact same commands on a brand new OCP `4.11.21` and was not able to reproduce the problem. I would double check if there is anything else on the k8s cluster that may initiate http connections to the Elasticsearch `Service`.

I'm closing since I don't believe it's a bug in ECK, feel free to open a new topic on [discuss](https://discuss.elastic.co/c/orchestration/eck/79) if you need more help.
Thanks

**Closed by barkbay** 2023-01-18 05:57 UTC
Labels: triage
