### ISSUE TITLE
ECK: set label to deployment or daemonset level

### ISSUE THREAD

**Issue by jelmokri** [elastic/cloud-on-k8s#6784] opened 2023-05-10 09:36 UTC
Hello everyone,

I don't find a way to set label to deployment or daemonset level when deploying elastic via eck.

I find the way to set label to pod level via PodTermplate section but didn't find a way to label object on of pod : deployment or daemonset.

is it possible ? if not do you plan to add it in next releases ?

thanks for your help

**Comment by thbkrkr** [comment] 2023-06-02 17:11
Duplicate of https://github.com/elastic/cloud-on-k8s/issues/2652, hence closing.

It is not yet possible and we have not yet found the right way to implement it to avoid orphans labels (check https://github.com/elastic/cloud-on-k8s/pull/3186#pullrequestreview-429546417).

**Closed by thbkrkr** 2023-06-02 17:11 UTC
Labels: triage
