### ISSUE TITLE
Readiness probe not working with custom container port

### ISSUE THREAD

**Issue by ibalat** [elastic/cloud-on-k8s#8042] opened 2024-09-04 07:59 UTC
Hi, I have upgraded 2.14 and it uses new readiness script checks 8080 port. But, we use 9200 port for elasticsearch container. How can I customize the script or is there another solution to solve the problem? I had updated readiness-port-script.sh with old readiness-probe-script.sh but it is not working because of missing env. At last status, pod is NotReady.

**readiness-port-script.sh**: `nc -z -v -w5 127.0.0.1 8080`

![Image](https://github.com/user-attachments/assets/69a96170-5bc4-429f-9916-393a7605962a)

Old version had used probe script but it is not working now because of missing environment variables ([#8009](https://github.com/elastic/cloud-on-k8s/pull/8009))
![Image](https://github.com/user-attachments/assets/eaca0707-996f-401e-8c8d-c7f295ac7b1f)

**Comment by ashuec90** [comment] 2024-09-05 18:45
I am also facing this issue just after disabling the xpack.security.http.ssl.enabled. and the readiness probe is failing with connection error.
```nc: connect to 127.0.0.1 port 8080 (tcp) failed: Connection refused```

**Comment by pebrc** [comment] 2024-09-06 07:28
@ibalat the container ports are irrelevant for the readiness check. It uses port 8080 on localhost. Don't update the readiness port script, don't override the readiness probe.  See the guidance in our docs https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-readiness.html#k8s_elasticsearch_versions_8_2_0_and_later

@ashuec90 this likely just means that your Elasticsearch pod is not ready. Check the logs.

**Comment by ibalat** [comment] 2024-09-06 10:54
@pebrc but no exposed 8080 port in container, how it check non-exists port? 8080 check return connection refused

**Comment by Mason0920** [comment] 2024-09-09 05:45
@pebrc 
[The document](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-readiness.html#k8s_elasticsearch_versions_8_2_0_and_later) says not to override the readiness probe, but I resolved the issue by overriding it as shown below.

```
        - name: elasticsearch
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - |
                  nc -z -v -w5 127.0.0.1 9200 #port change
```

**Comment by pebrc** [comment] 2024-09-09 06:51
@Mason0920 this is not doing what you think it is doing and you are putting the safe operation of the ECK operator at risk with this change. 

Elasticsearch will respond on 9200 as soon as the process is running. A main motivation for this change was to make sure that we consider nodes only ready when they actually have joined the cluster. Checking 9200 does not guarantee that. See the the following issues for more context https://github.com/elastic/cloud-on-k8s/issues/916 and https://github.com/elastic/cloud-on-k8s/issues/5449

@ibalat 8080 does not need to be exposed as a container port because this is a `exec` probe that runs locally inside the runnig container and uses localhost as mentioned before.

**Comment by ibalat** [comment] 2024-09-09 11:14
@pebrc yes, I don't need 8080 as exposed port but netstat output doesn't show 8080 port. I added outputs up comment. If 8080 port not exists, how can checkable? Am I missing something? Why 8080 port not exists in container :/

**Comment by ibalat** [comment] 2024-09-09 11:27
@pebrc I have only data pod and this pod's container has not 8080 port. Okey, I am not waiting 8080 to see at exposed port list but at this situation, how can 8080 check is available? Am I missing something? And my cluster is green

![Image](https://github.com/user-attachments/assets/04281f58-2451-4a20-83c0-8f53ac6246d5)

![Image](https://github.com/user-attachments/assets/398d9844-10c5-4ab8-b677-90f9776216e9)

```
127.0.0.1:57592 - 127.0.0.1:9200
127.0.0.1:34228 - 127.0.0.1:9200
127.0.0.1:37662 - 127.0.0.1:9200
127.0.0.1:57608 - 127.0.0.1:9200
127.0.0.1:52186 - 127.0.0.1:9200
```

**Comment by ibalat** [comment] 2024-09-11 07:50
sure, I can share.

**Elastic setup:**

```
resource "kubectl_manifest" "elasticsearch_dev" {
  yaml_body = file("${path.module}/config/elasticsearch/elasticsearch.yaml")
}
```

**elasticsearch.yaml**
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata: 
  name: elasticsearch-dev
  namespace: elasticsearch
spec:
  version: 8.13.4
  nodeSets:
  - name: data
    count: 1
    config:
      node.store.allow_mmap: false
      xpack.security.enabled: false
      xpack.ml.enabled: false
      xpack.graph.enabled: false
      xpack.watcher.enabled: false
      bootstrap.memory_lock: true
    volumeClaimTemplates:
    - metadata: 
        name: elasticsearch-data
      spec: 
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: gp3
    podTemplate:
      spec: 
        containers:
        - name: elasticsearch
           resources: 
            requests: 
              memory: 2800Mi
              cpu: "1"
            limits: 
              memory: 2800Mi
              cpu: "1200m"
        nodeSelector:
            elasticsearch: green
        tolerations: 
        - key: elasticsearch
          value: green
          effect: NoSchedule
  http: 
    tls:
      selfSignedCertificate: 
        disabled: true
    service:
      spec: 
        type: NodePort
```

**ECK operator:**
```
eck_operator_helm_config = {
    max_history      = 3
    version          = "2.14.0"
    create_namespace = true
    values           = [file("${path.module}/config/eck/eck-operator.yaml")]
  }
```

**eck-operator.yaml**
```
image:
  pullPolicy: "Always"
```

**Comment by harveyjing** [comment] 2024-09-13 01:48
Have the same problem. I ran three replicas. One pod is down because this readiness probe. `nc: connect to 127.0.0.1 port 8080 (tcp) failed: Connection refused`. I setuped with just two command. No other customizations.
```
helm install elastic-operator elastic/eck-operator -n elastic-stack --create-namespace --set=installCRDs=true

apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: elastic-stack
spec:
  version: 8.15.0
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
```
According this post https://www.elastic.co/blog/red-elasticsearch-cluster-panic-no-longer, I got some sessage:
```
curl -u "elastic:$PASSWORD" -k "https://localhost:9200/_cluster/allocation/explain?pretty"
{
  "note" : "No shard was specified in the explain API request, so this response explains a randomly chosen unassigned shard. There may be other unassigned shards in this cluster which cannot be assigned for different reasons. It may not be possible to assign this shard until one of the other shards is assigned correctly. To explain the allocation of other shards (whether assigned or unassigned) you must specify the target shard in the request to this API.",
  "index" : ".ds-filebeat-8.15.0-2024.09.09-000001",
  "shard" : 0,
  "primary" : true,
  "current_state" : "unassigned",
  "unassigned_info" : {
    "reason" : "NODE_LEFT",
    "at" : "2024-09-12T02:15:15.456Z",
    "details" : "node_left [0IKKAc4kRZm2qfN40WlJVA]",
    "last_allocation_status" : "no_valid_shard_copy"
  },
  "can_allocate" : "no_valid_shard_copy",
  "allocate_explanation" : "Elasticsearch can't allocate this shard because all the copies of its data in the cluster are stale or corrupt. Elasticsearch will allocate this shard when a node containing a good copy of its data joins the cluster. If no such node is available, restore this index from a recent snapshot.",
  "node_allocation_decisions" : [
    {
      "node_id" : "9o1iHmAGTo-vcZs4s3SIew",
      "node_name" : "quickstart-es-default-2",
      "transport_address" : "10.244.1.78:9300",
      "node_attributes" : {
        "ml.allocated_processors_double" : "4.0",
        "ml.machine_memory" : "2147483648",
        "ml.config_version" : "12.0.0",
        "ml.max_jvm_size" : "1073741824",
        "ml.allocated_processors" : "4",
        "xpack.installed" : "true",
        "transform.config_version" : "10.0.0",
        "k8s_node_name" : "worker03"
      },
      "roles" : [
        "data",
        "data_cold",
        "data_content",
        "data_frozen",
        "data_hot",
        "data_warm",
        "ingest",
        "master",
        "ml",
        "remote_cluster_client",
        "transform"
      ],
      "node_decision" : "no",
      "store" : {
        "in_sync" : false,
        "allocation_id" : "28a5a2__RVyR_VUV0ahEVA"
      }
    },
    {
      "node_id" : "_kAiqcc0RwCOysr3fypbsA",
      "node_name" : "quickstart-es-default-1",
      "transport_address" : "10.244.3.238:9300",
      "node_attributes" : {
        "ml.allocated_processors_double" : "4.0",
        "ml.machine_memory" : "2147483648",
        "ml.config_version" : "12.0.0",
        "ml.max_jvm_size" : "1073741824",
        "ml.allocated_processors" : "4",
        "xpack.installed" : "true",
        "transform.config_version" : "10.0.0",
        "k8s_node_name" : "worker01"
      },
      "roles" : [
        "data",
        "data_cold",
        "data_content",
        "data_frozen",
        "data_hot",
        "data_warm",
        "ingest",
        "master",
        "ml",
        "remote_cluster_client",
        "transform"
      ],
      "node_decision" : "no",
      "store" : {
        "in_sync" : false,
        "allocation_id" : "auY6WVS9SJKipfWHRD2Xqg"
      }
    }
  ]
}
```

**Comment by harveyjing** [comment] 2024-09-13 05:26
I found the root cause. After I restart the issue pod, I got the logs `Failed to load persistent cache`. And according this post https://opster.com/analysis/elasticsearch-failed-to-close-persistent-cache-index/, it mentioned some disk space clues. And I remeber that the initial PV size is only 1GB. After I increace the PV size. The pod is up and running!!!

**Comment by ibalat** [comment] 2024-09-19 06:03
@harveyjing I don't have any disk or another problem and my cluster is green, everything is ok, no error messages, although, 8080 port is not exists. I added some cluster details below:

```
nc -z -v -w5 127.0.0.1 8080
nc: connect to 127.0.0.1 port 8080 (tcp) failed: Connection refused
```

`/_cluster/health?filter_path=status,*_shards`:
```
{"status":"green","active_primary_shards":1610,"active_shards":1999,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0}
```

**Comment by harveyjing** [comment] 2024-09-19 06:50
![Image](https://github.com/user-attachments/assets/c8ca6c8c-df32-495f-aed9-ad3948b62882)
I can connect this port. My version is :
NAMESPACE       NAME         HEALTH   NODES   VERSION   PHASE   AGE
elastic-stack   quickstart   green    3       8.15.0    Ready   9d
@ibalat

**Comment by ibalat** [comment] 2024-09-24 12:20
my version 8.13.4, but is the reason that, I don't know :/

**Comment by jjnunogarcia** [comment] 2024-09-26 10:49
I'm experiencing the same issue when updating to 2.14.0, so I had to downgrade to 2.13.0, which seems to work.

**Comment by harveyjing** [comment] 2024-10-01 02:27
Maybe the issue is related with resources limitation, your hardware.

**Comment by vanthome** [comment] 2024-10-02 18:06
I had the same issue, for me version 8.15.1 did not even dare to open the port 8080 for health checking that's why they always failed. I have solved this in the same way as @Mason0920 suggested.

**Comment by maggieghamry** [comment] 2024-10-03 19:03
Observing same issue `8.15.0`

**Comment by pebrc** [comment] 2024-10-04 09:20
Please don't take this the wrong way but I am going to close this issue and block further comments. This is because this issue already causes a lot of confusion and creates the impression that there is a bug in ECK when at least to our current understanding and based on all the evidence brought forward in the discussion here there is not. If you have a new finding that indicates that there is indeed a bug in ECK you can always open a new issue.

Just to recap the main points for future readers coming here (and I will look into incorporating some if it in our docs):

### What does the following log statement mean?
```
nc: connect to 127.0.0.1 port 8080 (tcp) failed: Connection refused
``` 
It means Elasticsearch is not ready. There is no configuration error or similar, this is an expected log message.  It just means Elasticsearch has not reached the ready state. The reasons could be manifold @harveyjing for example mentioned not enough disk space.

### But 8080 is not exposed as a container port, how can this work?
It does not have to be because the kubelet runs `exec` readiness probes inside the container. No need to expose a port. 

### Regarding the OP
@ibalat in your example you turned `xpack.security.enabled` off. This is an [ECK managed setting](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-reserved-settings.html) that we don't recommend to change. Once you turn it on the readiness check will pass. However I admit that it seems odd that Elasticsearch does not report readiness when security is turned off. I will follow up with the Elasticsearch team to verify if this could be a bug in Elasticsearch itself.

**Closed by pebrc** 2024-10-04 09:20 UTC
Labels: triage

**Comment by kunisen** [comment] 2024-10-09 01:49
A little additional information to 8080 port:

### [1] It's a concept introduced by ES 

https://www.elastic.co/guide/en/elasticsearch/reference/current/advanced-configuration.html#readiness-tcp-port

To use it, user needs to set `readiness.port` in `elasticsearch.yml`

### [2] Motivation is to check if "a node has joined the cluster or not", but not only "node started"

https://www.elastic.co/guide/en/elasticsearch/reference/current/advanced-configuration.html#readiness-tcp-port

```
If configured, a node can open a TCP port when the node is in a ready state. 
A node is deemed ready when it has successfully joined a cluster. 
In a single node configuration, the node is said to be ready, when it’s able to accept requests.
```

### [3] In ECK, it's configured as `8080` in `readiness.port` in `elasticsearch.yml`

My test env:

```bash
# to check
➜  ~ kubectl get secret elasticsearch-quickstart-es-default-es-config -o jsonpath="{.data['elasticsearch\.yml']}" | base64 --decode | grep 8080 -B1    

# response
readiness:
    port: "8080"
```

### [4] Can check inside or outside the pod

Where we can get check when it's ready:

```bash
# inside the pod
elasticsearch@elasticsearch-quickstart-es-default-0:~$ nc -z -v -w5 127.0.0.1 8080
Connection to 127.0.0.1 8080 port [tcp/*] succeeded!

# outside the pod - check pod logs
➜  ~ k logs elasticsearch-quickstart-es-default-0 -c elasticsearch | grep 8080

{"@timestamp":"2024-10-09T01:20:33.805Z", "log.level": "INFO", "message":"readiness service up and running on 0.0.0.0:8080", "ecs.version": ...
```

**Comment by alxivanov** [comment] 2024-10-25 14:45
It may take a while for a node (pod) to become ready, provided all configuration is ok and there are no error/warn messages in pod log - in my case one of the nodes was "ready" 3 hours after it was restarted.

**Comment by fabienvauchelles** [comment] 2024-11-11 14:26
Hello,

If you deactivate the security (login/password), the probe doesn't work anymore:
```
xpack.security.enabled: false
```

Workaround is to change the port of the probe from 8080 to 9200 with:
```
podTemplate:
  spec:
    containers:
    - name: elasticsearch
      readinessProbe:
        exec:
          command:
            - bash
            - -c
            - "nc -z -v -w5 127.0.0.1 9200"
```

**Comment by bostrick** [comment] 2025-06-03 00:42
I think closing this issue is a mistake, as there is a real issue here, even if only a lack of communication.

I'm using an essentially pristine install using ECK operator 3.0.0 with default options (click, click, click...) on openshift (OCP) version 4.15.14 (upgrading to 4.15.51).  The 3 node v9.0.0 cluster has 9 indices and < 120k documents/300MB  total, and is less than a week old.  Previous restarts of elasticsearch pods have obtained ready state in seconds to 2 minutes at the most.

Upon upgrading OCP cluster from 4.15.14 to 4.15.51, upgrade has gone nominally, until vacating the first OCP node with an elasticsearch pod.  Pod was migrated to a new node, and all logs/events (other than the failed readiness check) seem to indicate successful startup, and all examination of /_cat interfaces seem to indicate a fully function cluster, but the pod has failed to obtain ready state.  Examining /proc/net/tcp{,6}, it is confirmed that there is no open port 8080.

If reading this thread correctly, and examining /mnt/elastic-internal/scripts/readiness-port-script.sh, "ready" is indicated by an open port 127.0.0.1:8080.  This is entirely opaque and gives no information as to why what seems a nominal working ES pod  doesn't think it is ready... no abnormal logs, no obvious abnormal /_cat messaging.  

I've been waiting 131 minutes for a ready state... something's not right.  Some condition must be preventing the advertising of a ready state... this condition needs to be surfaced.

I'll be happy to share more diagnostics if it is helpful.

(Kudo's, however, on the pod disruption budget which has stalled the OCP upgrade and left the ES cluster alive with two out of 3 ready pods... )

**Comment by avgerin0s** [comment] 2026-05-15 09:49
Not trying to necro-bump this but we stumbled upon this in a setup with `xpack.security.enabled: false`. I understand that it's not recommended to change this setting but since it is allowed I believe that the user should be able to spin up a cluster with this setting without issues.

After reading through @pebrc [comment](https://github.com/elastic/cloud-on-k8s/issues/8042#issuecomment-2393253868) I did a little research and I believe I found out why the ReadinessService does not reach its desired state:

In version 2.16.0[^1] the ECK operator started using the readiness TCP
API[^2] for ES cluster versions >= 8.2.

The previous check[^3] (and the one currently used by our setup for all
versions of clusters) used to check some layer7 information on port
:9200 - the default elasticsearch port. An elasticsearch node responds
to this port once it gets spinned up.

The new check[^4] performs a tcp check on port :8080 - which is the
readiness port. An elasticsearch node responds to this port once it
joins the cluster. That's the main rationale the ECK-operator authors
decided to change this.

When using the new readiness check with `xpack.security.enabled: false` it fails to make the
ES pod ready. Example:

```
my-cluster-eu-central-1a-1   0/1     Running   0          37m
```

Taking a look at the cluster metadata it points us to a parsing error related to the `role_mappings`:

```
...
"errors": { -
          "version": -1,
          "error_kind": "parsing",
          "errors": [ -
            "java.lang.IllegalStateException: Error processing state
            change request for file_settings, errors:
            org.elasticsearch.xcontent.XContentParseException: [1:138]
            [reserved_state_chunk] failed to parse field [state]\n\tat
            org.elasticsearch.xcontent@8.18.4/org.elasticsearch.xcontent.ObjectParser.throwFailedToParse(ObjectParser.java:620)\n\tat
            org.elasticsearch.xcontent@8.18.4/org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:615)\n\tat
            org.elasticsearch.xcontent@8.18.4/org.elasticsearch.xcontent.ObjectParser.parseSub(ObjectParser.java:633)\n\tat
            org.elasticsearch.xcontent@8.18.4/org.elasticsearch.xcontent.ObjectParser.parse(ObjectParser.java:316)\n\tat
            org.elasticsearch.xcontent@8.18.4/org.elasticsearch.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:167)\n\tat
            org.elasticsearch.xcontent@8.18.4/org.elasticsearch.xcontent.ConstructingObjectParser.apply(ConstructingObjectParser.java:159)\n\tat
            org.elasticsearch.server@8.18.4/org.elasticsearch.reservedstate.service.ReservedClusterStateService.parse(ReservedClusterStateService.java:111)\n\tat
            org.elasticsearch.server@8.18.4/org.elasticsearch.reservedstate.service.ReservedClusterStateService.process(ReservedClusterStateService.java:145)\n\tat
            org.elasticsearch.server@8.18.4/org.elasticsearch.reservedstate.service.FileSettingsService.processFileChanges(FileSettingsService.java:146)\n\tat
            org.elasticsearch.server@8.18.4/org.elasticsearch.reservedstate.service.FileSettingsService.processFileOnServiceStart(FileSettingsService.java:136)\n\tat
            org.elasticsearch.server@8.18.4/org.elasticsearch.common.file.AbstractFileWatchingService.processSettingsOnServiceStartAndNotifyListeners(AbstractFileWatchingService.java:306)\n\tat
            org.elasticsearch.server@8.18.4/org.elasticsearch.common.file.AbstractFileWatchingService.watcherThread(AbstractFileWatchingService.java:188)\n\tat
            java.base/java.lang.Thread.run(Thread.java:1447)\nCaused by:
            org.elasticsearch.xcontent.XContentParseException: [1:138]
            [state] failed to parse field [role_mappings]\n\tat\
            org.elasticsearch.xcontent@8.18.4/org.elasticsearch.xcontent.ObjectParser.rethrowFieldParseFailure(ObjectParser.java:558)\n\tat
            org.elasticsearch.xcontent@8.18.4/org.elasticsearch.xcontent.ObjectParser.lambda$declareNamedObjects$14(ObjectParser.java:498)\n\tat
            org.elasticsearch.xcontent@8.18.4/org.elasticsearch.xcontent.ObjectParser.lambda$declareNamedObjects$15(ObjectParser.java:509)\n\tat
            org.elasticsearch.xcontent@8.18.4/org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:613)\n\t...
            11 more\nCaused by: java.lang.IllegalStateException: Missing
            handler definition for content key [role_mappings]\n\tat
...
```

This setting is something the ECK operator provides[^6][^7], ignoring whether
security is enabled or not because it gets initialized as a
`map[string]interfae{}{}` which is NOT NULL:

```golang
// newEmptySettingsState returns an empty new Settings state.
func newEmptySettingsState() SettingsState {
	return SettingsState{
        ...
		RoleMappings:           &commonv1.Config{Data: map[string]interface{}{}},
        ...
	}
}

...

	if esConfigPolicy.SecurityRoleMappings != nil {
		state.RoleMappings = esConfigPolicy.SecurityRoleMappings
	}

...
```

```
elasticsearch@my-cluster-eu-central-1a-1:~$ cat config/operator/settings.json
{
  "metadata": {
    "version": "1754572651733675795",
    "compatibility": "8.6.1"
  },
  "state": {
    "cluster_settings": {},
    "snapshot_repositories": {},
    "slm": {},
    "role_mappings": {}, <--------
    "ilm": {},
    "ingest_pipelines": {},
    "index_templates": {
      "component_templates": {},
      "composable_index_templates": {}
    }
  }
}
```

Now Elasticsearch Security module registers[^8] handlers for this
configuration ONLY if its ENABLED:

```java
x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/Security.java:2417-2423:
List<ReservedClusterStateHandler<?>> reservedClusterStateHandlers() {
    if (enabled == false) {
        return Collections.emptyList();  // <----- no role_mappings handler
    }
    return List.of(reservedRoleMappingAction.get());
}
```

So in our case that leads to this exception we see in the cluster state
by this specific piece of code[^9]:

```java
server/src/main/java/org/elasticsearch/reservedstate/service/ReservedClusterStateService.java:99-105:
if (handlers.containsKey(name) == false) {
    throw new IllegalStateException("Missing handler definition for content key [" + name + "]");
}
```

Now, the ReadinessService gets involved because it needs - among other -
the file settings to be applied[^10][^11], which doesn't happen in our case:

```java
server/src/main/java/org/elasticsearch/readiness/ReadinessService.java:250-258:
boolean masterElected = ...;
boolean fileSettingsApplied = ...areFileSettingsApplied(...);
setReady(masterElected && fileSettingsApplied);  // ← both must be true

server/src/main/java/org/elasticsearch/readiness/ReadinessService.java::281-293:
protected boolean areFileSettingsApplied(ClusterState clusterState) {
    ReservedStateMetadata fileSettingsMetadata = clusterState.metadata()
        .reservedStateMetadata().get(FileSettingsService.NAMESPACE);
    if (fileSettingsMetadata == null) {
        return supportsFileSettings(clusterState) == false;
    } else {
        // metadata exists (error was written), but version == NO_VERSION → returns false
        return fileSettingsMetadata.version().equals(ReservedStateMetadata.NO_VERSION) == false;
    }
}
```

As a result the `setReady()` is always called with `false`, hence the ReadinessService never gets up.

So, to sum up, this ends with a node that:

- It's pod does not become ready
- The underlying node joins the cluster and starts getting shards
- Eventually getting a node with data on it crashed

Since elasticsearch let's the node join the cluster without the ReadinessService up I'm not sure that this is 100% an ECK operator bug or an ES one, though I believe that the `role_mappings` should be conditionally rendered in the operator provided settings to avoid this behavior.

Sorry for the long read :) 

[^1]: elastic/cloud-on-k8s#7847
[^2]: https://www.elastic.co/docs/reference/elasticsearch/configuration-reference/networking-settings#tcp-readiness-port
[^3]: https://github.com/elastic/cloud-on-k8s/blob/9e7b5d28331b32d7a6e8b0272161f7f6149d0f10/pkg/controller/elasticsearch/nodespec/readiness_probe.go#L54
[^4]: https://github.com/elastic/cloud-on-k8s/blob/9e7b5d28331b32d7a6e8b0272161f7f6149d0f10/pkg/controller/elasticsearch/nodespec/readiness_probe.go#L25
[^6]: https://github.com/elastic/cloud-on-k8s/blob/9e7b5d28331b32d7a6e8b0272161f7f6149d0f10/pkg/controller/elasticsearch/filesettings/file_settings.go#L68-L81
[^7]: https://github.com/elastic/cloud-on-k8s/blob/9e7b5d28331b32d7a6e8b0272161f7f6149d0f10/pkg/controller/elasticsearch/filesettings/file_settings.go#L109-L11
[^8]: https://github.com/elastic/elasticsearch/blob/43b24f613cf25fd3f3369df174e9535a99512aec/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/Security.java#L2417-L2423
[^9]: https://github.com/elastic/elasticsearch/blob/43b24f613cf25fd3f3369df174e9535a99512aec/server/src/main/java/org/elasticsearch/reservedstate/service/ReservedClusterStateService.java#L99-L102
[^10]: https://github.com/elastic/elasticsearch/blob/43b24f613cf25fd3f3369df174e9535a99512aec/server/src/main/java/org/elasticsearch/readiness/ReadinessService.java#L258
[^11]: https://github.com/elastic/elasticsearch/blob/43b24f613cf25fd3f3369df174e9535a99512aec/server/src/main/java/org/elasticsearch/readiness/ReadinessService.java#L281-L293
