### ISSUE TITLE
Cluster unhealthy because "license couldn't be updated"?

### ISSUE THREAD

**Issue by abh** [elastic/cloud-on-k8s#3122] opened 2020-05-20 20:12 UTC
## Bug Report
**What did you do?**

Running basic cluster from QuickStart.

**What did you expect to see?**

Cluster healthy.

**What did you see instead? Under which circumstances?**

```
  Warning  Unexpected  2m8s (x4 over 15m)  elasticsearch-controller  Could not update remote clusters in Elasticsearch settings
  Warning  Unexpected  2m8s (x2 over 10m)  elasticsearch-controller  Could not update cluster license: failed to revert to basic: Post https://logging-es-http.logging.svc:9200/_license/start_basic?acknowledge=true: dial tcp 10.43.79.133:9200: connect: connection timed out
  Warning  Unhealthy   2m8s                elasticsearch-controller  Elasticsearch cluster health degraded
```

The "remote clusters" issue looks like it was fixed in #3111.

When I try the /_license URL manually it doesn't time out (but gives a non-sensical response -- basic wasn't started because the license is basic?  I've no idea what this means or why I should care).

```
 curl -u elastic:...  -ks -XPOST https://logging-es-http.logging.svc:9200/_license/start_basic?acknowledge=true ; echo
{"acknowledged":true,"basic_was_started":false,"error_message":"Operation failed: Current license is basic."}
```

**Environment**

Bare metal / Rancher / RKE install.

* ECK version:

1.1.1

* Kubernetes information:

On premise; RKE, 1.17.5

* Logs:
```
{"log.level":"info","@timestamp":"2020-05-20T20:12:10.052Z","log.logger":"generic-reconciler","message":"Recoverable error during step, continuing","service.version":"1.1.1-b6f69fc4","service.type":"eck","ecs.version":"1.4.0","step":"reconcile-cluster-license","error":"failed to revert to basic: Post https://logging-es-http.logging.svc:9200/_license/start_basic?acknowledge=true: dial tcp 10.43.79.133:9200: connect: connection timed out","errorVerbose":"Post https://logging-es-http.logging.svc:9200/_license/start_basic?acknowledge=true: dial tcp 10.43.79.133:9200: connect: connection timed out\nfailed to revert to basic\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/license.startBasic\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/license/apply.go:78\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/license.applyLinkedLicense\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/license/apply.go:52\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/license.Reconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/license/reconcile.go:24\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver.(*defaultDriver).Reconcile.func1\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver/driver.go:203\ngithub.com/elastic/cloud-on-k8s/pkg/controller/common/reconciler.(*Results).Apply\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/common/reconciler/results.go:103\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver.(*defaultDriver).Reconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver/driver.go:196\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch.(*ReconcileElasticsearch).internalReconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/elasticsearch_controller.go:308\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch.(*ReconcileElasticsearch).Reconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/elasticsearch_controller.go:215\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"}
```

**Comment by abh** [comment] 2020-05-20 20:14
`get elastic` says

```
$ kubectl -n logging  get elastic
NAME                                                 HEALTH   NODES   VERSION   PHASE     AGE
elasticsearch.elasticsearch.k8s.elastic.co/logging   green    5       7.7.0     Invalid   104d
```

I tried upgrading from 7.6.2 to 7.7.0, but because the cluster is "invalid" it didn't actually do this.

**Comment by pebrc** [comment] 2020-05-25 09:01
The license error you are seeing are a consequence of a problem with your Elasticsearch cluster not the cause I would say. 

The fact the the cluster is marked as `Invalid` indicates that you tried to apply some form of invalid PodTemplate or Elasticsearch spec. 

Are you running ECK by any chance without the validating webhook?
It would also be interesting to:
* check the operator logs, as to what exactly the validation error was that made ECK mark your cluster as `Invalid`
* check that the Elasticsearch cluster is in fact healthy and reacheable from the operator process

We have some troubleshooting tips in the documentation here: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-troubleshooting.html

If you could share your Elasticsearch manifest that would probably also help elmininating the possibliity of an ECK bug.

**Comment by barkbay** [comment] 2020-06-04 07:23
Closing due to inactivity. Feel free to reopen if needed.

**Closed by barkbay** 2020-06-04 07:23 UTC
Labels: triage
