### ISSUE TITLE
Transient Settings Not Properly Removed on ECK Upgrade 2.x

### ISSUE THREAD

**Issue by BenB196** [elastic/cloud-on-k8s#5464] opened 2022-03-10 21:45 UTC
## Bug Report
**What did you do?**

Upgraded an ECK operator from `1.9.1` to `2.1.0`

**What did you expect to see?**

I expected to see the managed Elasticsearch cluster (`7.17.0`) successfully perform a rolling restart from the ECK operator upgrade.

**What did you see instead? Under which circumstances?**

I see the managed Elasticsearch cluster try to reallocate 350+ searchable snapshots from the restart of a `cold` node.

**Environment**

* ECK version: `2.1.0` (Helm Install)

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise yes
	* Cloud: GKE / EKS / AKS no
	* Kubernetes distribution: Openshift / Rancher / PKS v1.21.8+rke2r1
	
Having run into this searchable snapshot more than a few times before, I looked at the cluster settings and found the following transient setting set:

```json
{
  "transient" : {
    "cluster.routing.allocation.enable" : "all",
    "cluster.routing.allocation.exclude._name" : "none_excluded"
  }
}
```

Looking at: https://github.com/elastic/cloud-on-k8s/issues/4997 and https://github.com/elastic/cloud-on-k8s/pull/5072 it seems like it is intended for transient settings to no longer be used.

Assumption/hypothesis:

I seems like on the upgrade from 1.9.1 to 2.1.0, the transient setting was not properly removed by the operator before the rolling restart, and since it seems like these settings are no longer used, the ECK operator didn't take into account their existence before starting the restart, therefore causing the shards to relocate.

If this is the case, I'd consider it a bug as most people probably don't know that the operator used to set these transient values before hand, and there is nothing in the docs from what I can tell that mentions that a user must manually remove these settings.

Note: I went ahead and removed the settings manually:

```json
PUT _cluster/settings
{
"transient" : {
    "cluster" : {
      "routing" : {
        "allocation" : {
          "enable" : null,
          "exclude" : {
            "_name" : null
          }
        }
      }
    }
  }
}
```

And since removing them, they haven't come back like they'd normally do in `1.x`, so that is what leads me to this being an issue.

**Comment by barkbay** [comment] 2022-03-16 07:17
> the transient setting was not properly removed by the operator before the rolling restart, and since it seems like these settings are no longer used, the ECK operator didn't take into account their existence before starting the restart

There is no expectation from the user to remove them because  `"cluster.routing.allocation.enable" : "all"` is the default and leaving `"cluster.routing.allocation.exclude._name"` to `"none_excluded"` should not interfere with the use of the shutdown api ([introduced in ECK 2.0.0](https://www.elastic.co/guide/en/cloud-on-k8s/2.0/release-highlights-2.0.0.html#k8s-200-node-shutdown)).

> And since removing them, they haven't come back like they'd normally do in 1.x, so that is what leads me to this being an issue.

That's because ECK 2.0 ensures that those settings are set to some sane default values before completely stopping to manage them.

> I see the managed Elasticsearch cluster try to reallocate 350+ searchable snapshots from the restart of a cold node.

I'll try to reproduce by upgrading the operator from `1.9` to `2.0` with Elasticsearch 7.17.0 hosting a cold tier.

**Comment by barkbay** [comment] 2022-03-17 09:11
> I'll try to reproduce by upgrading the operator from 1.9 to 2.1 with Elasticsearch 7.17.0 hosting a cold tier.

I can confirm that I have observed some shards being relocated, while I think it should not be the case. I have opened an issue in the Elasticsearch repo to understand if it is an expected behaviour: https://github.com/elastic/elasticsearch/issues/85052

**Comment by BenB196** [comment] 2022-03-17 11:30
A follow up question until what appears to be an underlying issue with the shutdown API. Could the normal rolling upgrade setting of: 

```json
PUT _cluster/settings
{
  "persistent": {
    "cluster.routing.allocation.enable": "primaries"
  }
}
```

Be applied before a rolling restart is started by the ECK operator to prevent this issue?

**Comment by barkbay** [comment] 2022-03-17 14:02
> Be applied before a rolling restart is started by the ECK operator to prevent this issue?

Yes, however the purpose of the shutdown API is to avoid to manage the cluster settings by using a dedicated lifecycle API.

**Comment by barkbay** [comment] 2022-04-12 08:04
I'm closing because I think the root cause if your issue is now tracked with this Elasticsearch issue: https://github.com/elastic/elasticsearch/issues/85052

**Closed by barkbay** 2022-04-12 08:04 UTC
Labels: triage
