### ISSUE TITLE
failed to setup automated snapshot using elastic operator

### ISSUE THREAD

**Issue by Braineanear** [elastic/cloud-on-k8s#6259] opened 2022-12-26 18:57 UTC
## Bug Report
**What did you do?**
I'm launching 3 elastic nodes using elastic operator and i tried to set up automated snapshots for these instances.

I followed this https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-snapshots.html

I minified the json of the service account key and created a file called gcs.client.default.credentials_file with no file extension and added this file to kubernetes secrets.

And added the secureSettings.secretName field to the spec of the elastic cluster and added the secret name to it which was gcs-credentials

**Environment**

* ECK version: 8.5.3

* Kubernetes information:
	* Cloud: GKE v1.23.11-gke.300
    
* Logs:

```json
{
    "@timestamp": "2022-12-26T18:45:40.037Z",
    "log.level": "ERROR",
    "message": "fatal exception while booting Elasticsearch",
    "ecs.version": "1.2.0",
    "[service.name](https://service.name/)": "ES_ECS",
    "event.dataset": "elasticsearch.server",
    "[process.thread.name](https://process.thread.name/)": "main",
    "log.logger": "org.elasticsearch.bootstrap.Elasticsearch",
    "[elasticsearch.node.name](https://elasticsearch.node.name/)": "elasticsearch-cluster-es-node-1",
    "[elasticsearch.cluster.name](https://elasticsearch.cluster.name/)": "elasticsearch-cluster",
    "error.type": "java.lang.IllegalStateException",
    "error.message": "failed to load plugin class [org.elasticsearch.repositories.gcs.GoogleCloudStoragePlugin]",
    "error.stack_trace": "java.lang.IllegalStateException: failed to load plugin class [org.elasticsearch.repositories.gcs.GoogleCloudStoragePlugin]
        at org.elasticsearch.server@8.5.0/org.elasticsearch.plugins.PluginsService.loadPlugin([PluginsService.java:607](https://pluginsservice.java:607/))
        at org.elasticsearch.server@8.5.0/org.elasticsearch.plugins.PluginsService.loadBundle([PluginsService.java:482](https://pluginsservice.java:482/))
        at org.elasticsearch.server@8.5.0/org.elasticsearch.plugins.PluginsService.loadBundles([PluginsService.java:290](https://pluginsservice.java:290/))
        at org.elasticsearch.server@8.5.0/org.elasticsearch.plugins.PluginsService.<init>([PluginsService.java:159](https://pluginsservice.java:159/))
        at org.elasticsearch.server@8.5.0/org.elasticsearch.plugins.PluginsService.lambda$getPluginsServiceCtor$14([PluginsService.java:634](https://pluginsservice.java:634/))
        at org.elasticsearch.server@8.5.0/org.elasticsearch.node.Node.<init>([Node.java:406](https://node.java:406/))
        at org.elasticsearch.server@8.5.0/org.elasticsearch.node.Node.<init>([Node.java:316](https://node.java:316/))
        at org.elasticsearch.server@8.5.0/org.elasticsearch.bootstrap.Elasticsearch$2.<init>([Elasticsearch.java:214](https://elasticsearch.java:214/))
        at org.elasticsearch.server@8.5.0/org.elasticsearch.bootstrap.Elasticsearch.initPhase3([Elasticsearch.java:214](https://elasticsearch.java:214/))
        at org.elasticsearch.server@8.5.0/org.elasticsearch.bootstrap.Elasticsearch.main([Elasticsearch.java:67](https://elasticsearch.java:67/))
    Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance([DirectConstructorHandleAccessor.java:79](https://directconstructorhandleaccessor.java:79/))
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller([Constructor.java:500](https://constructor.java:500/))
        at java.base/java.lang.reflect.Constructor.newInstance([Constructor.java:484](https://constructor.java:484/))
        at org.elasticsearch.server@8.5.0/org.elasticsearch.plugins.PluginsService.loadPlugin([PluginsService.java:600](https://pluginsservice.java:600/))
        ... 9 more
    Caused by: java.lang.IllegalArgumentException: failed to load GCS client credentials from [gcs.client.default.credentials_file]
        at org.elasticsearch.repositories.gcs.GoogleCloudStorageClientSettings.loadCredential([GoogleCloudStorageClientSettings.java:265](https://googlecloudstorageclientsettings.java:265/))
        at org.elasticsearch.repositories.gcs.GoogleCloudStorageClientSettings.getClientSettings([GoogleCloudStorageClientSettings.java:221](https://googlecloudstorageclientsettings.java:221/))
        at org.elasticsearch.repositories.gcs.GoogleCloudStorageClientSettings.load([GoogleCloudStorageClientSettings.java:209](https://googlecloudstorageclientsettings.java:209/))
        at org.elasticsearch.repositories.gcs.GoogleCloudStoragePlugin.reload([GoogleCloudStoragePlugin.java:88](https://googlecloudstorageplugin.java:88/))
        at org.elasticsearch.repositories.gcs.GoogleCloudStoragePlugin.<init>([GoogleCloudStoragePlugin.java:36](https://googlecloudstorageplugin.java:36/))
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance([DirectConstructorHandleAccessor.java:67](https://directconstructorhandleaccessor.java:67/))
        ... 12 more
    Caused by: java.io.IOException: Invalid PKCS#8 data.
        at com.google.auth.oauth2.ServiceAccountCredentials.privateKeyFromPkcs8([ServiceAccountCredentials.java:496](https://serviceaccountcredentials.java:496/))
        at com.google.auth.oauth2.ServiceAccountCredentials.fromPkcs8([ServiceAccountCredentials.java:474](https://serviceaccountcredentials.java:474/))
        at com.google.auth.oauth2.ServiceAccountCredentials.fromJson([ServiceAccountCredentials.java:212](https://serviceaccountcredentials.java:212/))
        at com.google.auth.oauth2.ServiceAccountCredentials.fromStream([ServiceAccountCredentials.java:548](https://serviceaccountcredentials.java:548/))
        at com.google.auth.oauth2.ServiceAccountCredentials.fromStream([ServiceAccountCredentials.java:520](https://serviceaccountcredentials.java:520/))
        at org.elasticsearch.repositories.gcs.GoogleCloudStorageClientSettings.lambda$loadCredential$13([GoogleCloudStorageClientSettings.java:257](https://googlecloudstorageclientsettings.java:257/))
        at java.base/java.security.AccessController.doPrivileged([AccessController.java:569](https://accesscontroller.java:569/))
        at org.elasticsearch.repositories.gcs.SocketAccess.doPrivilegedIOException([SocketAccess.java:33](https://socketaccess.java:33/))
        at org.elasticsearch.repositories.gcs.GoogleCloudStorageClientSettings.loadCredential([GoogleCloudStorageClientSettings.java:256](https://googlecloudstorageclientsettings.java:256/))
        ... 17 more
    "
}

ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/elasticsearch-cluster.log
```

**Comment by thbkrkr** [comment] 2023-02-15 14:16
Seeing `Caused by: java.io.IOException: Invalid PKCS#8 data.`, you need to double check the content of your secret `gcs.client.default.credentials_file` because there is an issue.

I'm closing since I don't believe it's a bug in ECK, feel free to open a new topic on [discuss](https://discuss.elastic.co/c/orchestration/eck/79) if you need more help.

**Closed by thbkrkr** 2023-02-15 14:16 UTC
Labels: triage
