### ISSUE TITLE
Not able access Kibana using domain

### ISSUE THREAD

**Issue by swvaibhav** [elastic/cloud-on-k8s#1922] opened 2019-10-08 12:18 UTC
I have just deployed, Elastic Cloud on Kubernetes (ECK) and not able to access Kibana on the public URL. I have also set up an Ingress to access Kibana using the domain.

Also, when using Kibana 7.2.0 the pod keeps on crashing with error message `Kibana should not be run as root.  Use --allow-root to continue.`

```yaml
apiVersion: kibana.k8s.elastic.co/v1alpha1
kind: Kibana
metadata:
  name: eck-kibana
  namespace: vulcan
spec:
  version: 7.1.0
  imagePullPolicy: Always
  nodeCount: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  elasticsearchRef:
    name: eck-elastic
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eck-kibana-ingress
  namespace: vulcan
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - secretName: eduqfix-tls-cert
  rules:
  - host: ecktest.eduqfix.com
    http:
      paths:
      - path: /
        backend:
          serviceName: eck-kibana-kb-http
          servicePort: 5601
```

**Comment by anyasabo** [comment] 2019-10-08 22:36
What happens when you attempt to access it? If you can also share the ECK version you are using it would help us try to reproduce it.

>Also, when using Kibana 7.2.0 the pod keeps on crashing with error message Kibana should not be run as root. Use --allow-root to continue.

Can you please open up a separate issue with the spec you used to create this? I tried to reproduce it and was unable to. Similarly please share the ECK version as well.

**Comment by pebrc** [comment] 2019-10-09 10:16
@swvaibhav I tried your example (on latetest master) and it works for me if I leave out ` nginx.ingress.kubernetes.io/rewrite-target: /$2` otherwise I get a redirect loop. 

I tried both 7.1.0 and 7.20. 

So I am tempted to close this, please reopen if needed.

**Closed by pebrc** 2019-10-09 10:16 UTC

**Comment by swvaibhav** [comment] 2019-10-10 12:09
@pebrc Yes, when I removed the `nginx.ingress.kubernetes.io/rewrite-target: /$2` annotation, I was able to access the Kibana, however, I still think it is not possible to access it on a subpath say `https://www.example.com/eck`
