### ISSUE TITLE
Unable to create elasticsearch when requiring specific labels

### ISSUE THREAD

**Issue by tschroeder-zendesk** [elastic/cloud-on-k8s#3990] opened 2020-11-28 23:59 UTC
## Proposal

In our kubernetes cluster there is a requirement that every resource needs to be labeled with both project and team. The issue is that I cannot seem to be able to set the labels I think for the headless service for the pods as best I can tell from tracing through the code.

## Bug Report
**What did you do?**
 I have defined the following:
```
"apiVersion": "elasticsearch.k8s.elastic.co/v1"
"kind": "Elasticsearch"
"metadata":
  "labels":
    "product": "support"
    "project": "atlas-elasticsearch"
    "role": "operator"
    "team": "atlas"
  "name": "quickstart"
  "namespace": "atlas-elasticsearch"
"spec":
  "http":
    "service":
      "metadata":
        "labels":
          "product": "support"
          "project": "atlas-elasticsearch"
          "role": "operator"
          "team": "atlas"
  "nodeSets":
  - "config":
      "node.store.allow_mmap": false
    "count": 1
    "name": "mynodes"
    "podTemplate":
      "metadata":
        "labels":
          "product": "support"
          "project": "atlas-elasticsearch"
          "role": "operator"
          "team": "atlas"
    "volumeClaimTemplates":
    - "metadata":
        "labels":
          "product": "support"
          "project": "atlas-elasticsearch"
          "role": "operator"
          "team": "atlas"
        "name": "elasticsearch-data"
  "podDisruptionBudget": {}
  "transport":
    "service":
      "metadata":
        "labels":
          "product": "support"
          "project": "atlas-elasticsearch"
          "role": "operator"
          "team": "atlas"
  "version": "7.10.0"
...
```
Setting this fails

**What did you expect to see?**

**What did you see instead? Under which circumstances?**
```
{
  "log.level":"error",
  "@timestamp":"2020-11-28T23:36:23.594Z",
  "log.logger":"controller",
  "message":"Reconciler error",
  "service.version":"1.3.0+6db1914b",
  "service.type":"eck",
  "ecs.version":"1.4.0",
  "controller":"elasticsearch-controller",
  "name":"quickstart",
  "namespace":"atlas-elasticsearch",
  "error":"reconcile service: admission webhook \"validation.gatekeeper.sh\" denied the request: [denied by core-must-have-project] REDACTED Service atlas-elasticsearch quickstart-es-mynodes: you must provide labels {\"project\", \"team\"}.",
  "errorCauses":[
    {
      "error":"reconcile service: admission webhook \"validation.gatekeeper.sh\" denied the request: [denied by core-must-have-project] REDACTED Service atlas-elasticsearch quickstart-es-mynodes: you must provide labels {\"project\", \"team\"}."
     }
  ],
  "error.stack_trace":"REDACTED"
}
```
**Environment**

* ECK version: 1.3.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
if relevant insert the resource definition
```

* Logs:
```
insert operator logs or any relevant message to the issue here
```

**Comment by sebgl** [comment] 2020-11-30 08:08
The service that fails creation is the StatefulSet headless service we create for `quickstart-es-mynodes`. For which indeed, you cannot specify labels currently.

This is duplicate of https://github.com/elastic/cloud-on-k8s/issues/2652.

**Closed by sebgl** 2020-11-30 08:08 UTC
Labels: >enhancement
