### ISSUE TITLE
elastic-agent healthy but no logs and metrics with all operation skipped

### ISSUE THREAD

**Issue by veezhang** [elastic/cloud-on-k8s#5188] opened 2021-12-21 13:03 UTC
## Bug Report
**What did you do?**

I have create `elastic-agent` with the following **Resource definition**. 

`elastic-agent` goes healthy but there no logs and metrics index.

**What did you expect to see?**

Upload logs and metrics correctly.

* ECK version:

1.9.1

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* Cloud: AKS
```
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"802eff1fe87ad2dd737ebbe891f30500b88beb00", GitTreeState:"clean", BuildDate:"2021-11-15T08:35:41Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
# kibana.yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elasticsearch
spec:
  version: 7.16.2
  count: 2
  config:
    xpack.fleet.agents.elasticsearch.host: "https://elasticsearch-es-http.elasticsearch.svc:9200"
    xpack.fleet.agents.fleet_server.hosts: ["https://fleet-server-agent-http.elasticsearch.svc:8220"]
    xpack.fleet.packages:
      - name: kubernetes
        version: 0.14.0
    xpack.fleet.agentPolicies:
      - name: Default Fleet Server on ECK policy
        id: Default Fleet Server on ECK policy
        is_default_fleet_server: true
        package_policies:
          - package:
              name: fleet_server
            name: fleet_server-1
      - name: Default Elastic Agent on ECK policy
        id: Default Elastic Agent on ECK policy
        is_default: true
        unenroll_timeout: 900
        package_policies:
          - package:
              name: system
            name: system-1
          - package:
              name: kubernetes
            name: kubernetes-1
  elasticsearchRef:
    name: elasticsearch

# elastic-agent.yaml
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: elastic-agent
  namespace: elasticsearch
spec:
  version: 7.16.2
  kibanaRef:
    name: kibana
  fleetServerRef:
    name: fleet-server
  mode: fleet
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: elastic-agent
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastic-agent
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
      - namespaces
      - events
      - services
      - configmaps
    verbs:
      - get
      - watch
      - list
  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs:
      - get
      - create
      - update
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
  - apiGroups: ["extensions"]
    resources:
      - replicasets
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "apps"
    resources:
      - statefulsets
      - deployments
      - replicasets
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - nodes/stats
    verbs:
      - get
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - "get"
      - "list"
      - "watch"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-agent
  namespace: elasticsearch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic-agent
subjects:
  - kind: ServiceAccount
    name: elastic-agent
    namespace: elasticsearch
roleRef:
  kind: ClusterRole
  name: elastic-agent
  apiGroup: rbac.authorization.k8s.io

# fleet-server.yaml
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server
  namespace: elasticsearch
spec:
  version: 7.16.2
  kibanaRef:
    name: kibana
  elasticsearchRefs:
    - name: elasticsearch
  mode: fleet
  fleetServerEnabled: true
  deployment:
    replicas: 1
    podTemplate:
      spec:
        serviceAccountName: fleet-server
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleet-server
rules:
  - apiGroups: [""]
    resources:
      - pods
      - namespaces
      - nodes
    verbs:
      - get
      - watch
      - list
  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs:
      - get
      - create
      - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-server
  namespace: elasticsearch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fleet-server
subjects:
  - kind: ServiceAccount
    name: fleet-server
    namespace: elasticsearch
roleRef:
  kind: ClusterRole
  name: fleet-server
  apiGroup: rbac.authorization.k8s.io
```

* Logs:
```

Performing setup of Fleet in Kibana

Policy selected for enrollment:  Default Elastic Agent on ECK policy
2021-12-21T12:38:57.119Z        INFO    cmd/enroll_cmd.go:454   Starting enrollment to URL: https://fleet-server-agent-http.elasticsearch.svc:8220/
2021-12-21T12:38:58.049Z        INFO    cmd/enroll_cmd.go:252   Elastic Agent might not be running; unable to trigger restart
Successfully enrolled the Elastic Agent.
2021-12-21T12:38:58.158Z        INFO    application/application.go:67   Detecting execution mode
2021-12-21T12:38:58.159Z        INFO    application/application.go:92   Agent is managed by Fleet
2021-12-21T12:38:58.159Z        INFO    capabilities/capabilities.go:59 capabilities file not found in /usr/share/elastic-agent/capabilities.yml
I1221 12:38:58.943531      14 leaderelection.go:243] attempting to acquire leader lease elasticsearch/elastic-agent-cluster-leader...
2021-12-21T12:38:59.045Z        INFO    [composable.providers.docker]   docker/docker.go:43     Docker provider skipped, unable to connect: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
2021-12-21T12:38:59.046Z        INFO    [composable.providers.kubernetes]       kubernetes/kubernetes.go:90     Kubernetes provider started for resource pod with node scope
2021-12-21T12:38:59.064Z        INFO    [composable.providers.kubernetes]       kubernetes/util.go:146  kubernetes: Node aks-nodepool1-25688326-vmss000001 discovered by NODE_NAME environment variable
2021-12-21T12:38:59.393Z        INFO    [composable.providers.kubernetes]       kubernetes/kubernetes.go:90     Kubernetes provider started for resource node with node scope
2021-12-21T12:38:59.393Z        INFO    [composable.providers.kubernetes]       kubernetes/util.go:122  kubernetes: Using node aks-nodepool1-25688326-vmss000001 provided in the config
2021-12-21T12:38:59.504Z        INFO    [api]   api/server.go:62        Starting stats endpoint
2021-12-21T12:38:59.504Z        INFO    application/managed_mode.go:291 Agent is starting
2021-12-21T12:38:59.504Z        INFO    [api]   api/server.go:64        Metrics endpoint listening on: /usr/share/elastic-agent/state/data/tmp/elastic-agent.sock (configured: unix:///usr/share/elastic-agent/state/data/tmp/elastic-agent.sock)
2021-12-21T12:39:01.714Z        INFO    stateresolver/stateresolver.go:48       New State ID is vd_OOzSk
2021-12-21T12:39:01.714Z        INFO    stateresolver/stateresolver.go:49       Converging state requires execution of 3 step(s)
2021-12-21T12:39:16.912Z        INFO    log/reporter.go:40      2021-12-21T12:39:16Z - message: Application: metricbeat--7.16.2[e48cda89-30c7-48d1-9e6f-930e1a7508b2]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
2021-12-21T12:39:21.520Z        INFO    log/reporter.go:40      2021-12-21T12:39:21Z - message: Application: metricbeat--7.16.2[e48cda89-30c7-48d1-9e6f-930e1a7508b2]: State changed to CONFIG: Updating configuration - type: 'STATE' - sub_type: 'CONFIG'
2021-12-21T12:39:22.610Z        INFO    log/reporter.go:40      2021-12-21T12:39:22Z - message: Application: metricbeat--7.16.2[e48cda89-30c7-48d1-9e6f-930e1a7508b2]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
2021-12-21T12:39:37.931Z        INFO    log/reporter.go:40      2021-12-21T12:39:37Z - message: Application: filebeat--7.16.2[e48cda89-30c7-48d1-9e6f-930e1a7508b2]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
2021-12-21T12:39:40.216Z        INFO    operation/operator.go:284       operation 'operation-install' skipped for filebeat.7.16.2
2021-12-21T12:39:41.117Z        INFO    log/reporter.go:40      2021-12-21T12:39:41Z - message: Application: filebeat--7.16.2[e48cda89-30c7-48d1-9e6f-930e1a7508b2]: State changed to CONFIG: Updating configuration - type: 'STATE' - sub_type: 'CONFIG'
2021-12-21T12:39:41.617Z        INFO    log/reporter.go:40      2021-12-21T12:39:41Z - message: Application: filebeat--7.16.2[e48cda89-30c7-48d1-9e6f-930e1a7508b2]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
2021-12-21T12:39:42.610Z        INFO    log/reporter.go:40      2021-12-21T12:39:42Z - message: Application: filebeat--7.16.2--36643631373035623733363936343635[e48cda89-30c7-48d1-9e6f-930e1a7508b2]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
2021-12-21T12:39:44.912Z        INFO    operation/operator.go:284       operation 'operation-install' skipped for metricbeat.7.16.2
2021-12-21T12:39:45.611Z        INFO    log/reporter.go:40      2021-12-21T12:39:45Z - message: Application: filebeat--7.16.2--36643631373035623733363936343635[e48cda89-30c7-48d1-9e6f-930e1a7508b2]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
2021-12-21T12:39:48.216Z        INFO    log/reporter.go:40      2021-12-21T12:39:48Z - message: Application: metricbeat--7.16.2--36643631373035623733363936343635[e48cda89-30c7-48d1-9e6f-930e1a7508b2]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
2021-12-21T12:39:48.219Z        INFO    stateresolver/stateresolver.go:66       Updating internal state
2021-12-21T12:39:49.311Z        INFO    stateresolver/stateresolver.go:48       New State ID is vd_OOzSk
2021-12-21T12:39:49.311Z        INFO    stateresolver/stateresolver.go:49       Converging state requires execution of 3 step(s)
2021-12-21T12:39:51.815Z        INFO    log/reporter.go:40      2021-12-21T12:39:51Z - message: Application: metricbeat--7.16.2--36643631373035623733363936343635[e48cda89-30c7-48d1-9e6f-930e1a7508b2]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
2021-12-21T12:39:52.217Z        INFO    operation/operator.go:284       operation 'operation-install' skipped for metricbeat.7.16.2
2021-12-21T12:39:52.217Z        INFO    operation/operator.go:284       operation 'operation-start' skipped for metricbeat.7.16.2
I1221 12:39:53.209835      14 leaderelection.go:253] successfully acquired lease elasticsearch/elastic-agent-cluster-leader
2021-12-21T12:39:53.710Z        INFO    operation/operator.go:284       operation 'operation-install' skipped for filebeat.7.16.2
2021-12-21T12:39:53.710Z        INFO    operation/operator.go:284       operation 'operation-start' skipped for filebeat.7.16.2
2021-12-21T12:39:54.910Z        INFO    operation/operator.go:284       operation 'operation-install' skipped for filebeat.7.16.2
2021-12-21T12:39:54.910Z        INFO    operation/operator.go:284       operation 'operation-start' skipped for filebeat.7.16.2
2021-12-21T12:39:56.121Z        INFO    operation/operator.go:284       operation 'operation-install' skipped for metricbeat.7.16.2
2021-12-21T12:39:56.121Z        INFO    operation/operator.go:284       operation 'operation-start' skipped for metricbeat.7.16.2
2021-12-21T12:39:56.124Z        INFO    stateresolver/stateresolver.go:66       Updating internal state
```

**Comment by barkbay** [comment] 2022-01-06 08:45
Just tried myself on AKS with the exact same resource definitions and it's working as expected:

```
GET _cat/indices?v=true

health status index                                                             uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   .ds-metrics-elastic_agent.filebeat-default-2022.01.06-000001      nVM_SXgRSVagnhSPsTyqRA   1   1        200            0    426.1kb        230.8kb
green  open   .ds-metrics-system.cpu-default-2022.01.06-000001                  myII2SS8Q6KOF52wvBIIdA   1   1        106            0    559.2kb        320.8kb
green  open   .fleet-agents-7                                                   mHatuDw8Tp63tTMXh2SFlg   1   1          4          104    466.1kb        244.3kb
green  open   .ds-metrics-elastic_agent.metricbeat-default-2022.01.06-000001    ZY5J23MqTu69PZ8W2MfGew   1   1        200            0    602.2kb        287.7kb
green  open   .ds-metrics-elastic_agent.fleet_server-default-2022.01.06-000001  NlAQoV-gRT-C7jDMTh0QUQ   1   1         74            0    267.5kb
....
```

Note that I also have those "skipped" messages but they seem harmless:

```
2022-01-06T08:33:24.483Z	INFO	stateresolver/stateresolver.go:48	New State ID is 5yLSNXoJ
2022-01-06T08:33:24.483Z	INFO	stateresolver/stateresolver.go:49	Converging state requires execution of 3 step(s)
2022-01-06T08:33:40.092Z	INFO	log/reporter.go:40	2022-01-06T08:33:40Z - message: Application: filebeat--7.16.2[f931e740-ab84-4a5d-b42b-04c9e89426fb]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
2022-01-06T08:33:43.478Z	INFO	log/reporter.go:40	2022-01-06T08:33:43Z - message: Application: filebeat--7.16.2[f931e740-ab84-4a5d-b42b-04c9e89426fb]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
2022-01-06T08:33:57.477Z	INFO	log/reporter.go:40	2022-01-06T08:33:57Z - message: Application: metricbeat--7.16.2[f931e740-ab84-4a5d-b42b-04c9e89426fb]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
2022-01-06T08:33:59.285Z	INFO	operation/operator.go:284	operation 'operation-install' skipped for filebeat.7.16.2
2022-01-06T08:34:01.878Z	INFO	log/reporter.go:40	2022-01-06T08:34:01Z - message: Application: metricbeat--7.16.2[f931e740-ab84-4a5d-b42b-04c9e89426fb]: State changed to CONFIG: Updating configuration - type: 'STATE' - sub_type: 'CONFIG'
2022-01-06T08:34:02.378Z	INFO	log/reporter.go:40	2022-01-06T08:34:02Z - message: Application: metricbeat--7.16.2[f931e740-ab84-4a5d-b42b-04c9e89426fb]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
2022-01-06T08:34:02.985Z	INFO	log/reporter.go:40	2022-01-06T08:34:02Z - message: Application: filebeat--7.16.2--36643631373035623733363936343635[f931e740-ab84-4a5d-b42b-04c9e89426fb]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
2022-01-06T08:34:05.786Z	INFO	operation/operator.go:284	operation 'operation-install' skipped for metricbeat.7.16.2
2022-01-06T08:34:06.584Z	INFO	log/reporter.go:40	2022-01-06T08:34:06Z - message: Application: metricbeat--7.16.2--36643631373035623733363936343635[f931e740-ab84-4a5d-b42b-04c9e89426fb]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
2022-01-06T08:34:06.586Z	INFO	stateresolver/stateresolver.go:66	Updating internal state
2022-01-06T08:34:06.680Z	INFO	log/reporter.go:40	2022-01-06T08:34:06Z - message: Application: filebeat--7.16.2--36643631373035623733363936343635[f931e740-ab84-4a5d-b42b-04c9e89426fb]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
2022-01-06T08:34:09.380Z	INFO	log/reporter.go:40	2022-01-06T08:34:09Z - message: Application: metricbeat--7.16.2--36643631373035623733363936343635[f931e740-ab84-4a5d-b42b-04c9e89426fb]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
2022-01-06T08:35:23.184Z	INFO	stateresolver/stateresolver.go:48	New State ID is 5yLSNXoJ
2022-01-06T08:35:23.184Z	INFO	stateresolver/stateresolver.go:49	Converging state requires execution of 3 step(s)
2022-01-06T08:35:24.295Z	INFO	operation/operator.go:284	operation 'operation-install' skipped for filebeat.7.16.2
2022-01-06T08:35:24.295Z	INFO	operation/operator.go:284	operation 'operation-start' skipped for filebeat.7.16.2
2022-01-06T08:35:25.485Z	INFO	operation/operator.go:284	operation 'operation-install' skipped for metricbeat.7.16.2
2022-01-06T08:35:25.485Z	INFO	operation/operator.go:284	operation 'operation-start' skipped for metricbeat.7.16.2
2022-01-06T08:35:26.585Z	INFO	operation/operator.go:284	operation 'operation-install' skipped for filebeat.7.16.2
2022-01-06T08:35:26.585Z	INFO	operation/operator.go:284	operation 'operation-start' skipped for filebeat.7.16.2
2022-01-06T08:35:27.793Z	INFO	operation/operator.go:284	operation 'operation-install' skipped for metricbeat.7.16.2
2022-01-06T08:35:27.793Z	INFO	operation/operator.go:284	operation 'operation-start' skipped for metricbeat.7.16.2
2022-01-06T08:35:27.795Z	INFO	stateresolver/stateresolver.go:66	Updating internal state
```

May I ask you to open a new topic [here](https://discuss.elastic.co/tags/c/observability/82/fleet) as I don't think the problem is related to the operator itself ?

Thanks

**Comment by pebrc** [comment] 2022-01-17 10:51
I am closing this based on @barkbay 's experiment. Let's continue the discussion on https://discuss.elastic.co/tags/c/observability/82/fleet if necessary.

**Closed by pebrc** 2022-01-17 10:51 UTC
Labels: triage
