### ISSUE TITLE
Elasticsearch Monitoring 

### ISSUE THREAD

**Issue by farazmujtaba** [elastic/cloud-on-k8s#2059] opened 2019-10-24 23:00 UTC
!-- Bug report -->
## Bug Report
**What did you do?**
Deployed zone-aware ES 7.4 using V1beta1 operator API 
**What did you expect to see?**
Monitoring data when "xpack.monitoring.elasticsearch.collection.enabled"is set to true
**What did you see instead? Under which circumstances?**
Kibana error "We couldn't activate monitoring"

**Environment**
Google Cloud public GKE 1.13.10-gke.0

* ECK version:

apiVersion: elasticsearch.k8s.elastic.co/v1beta1

* Kubernetes information:

Google Cloud public GKE 1.13.10-gke.0 deployed in regional cluster
	

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-gke.0", GitCommit:"569511c9540f78a94cc6a41d895c382d0946c11a", GitTreeState:"clean", BuildDate:"2019-08-21T23:28:44Z", GoVersion:"go1.11.13b4", Compiler:"gc", Platform:"linux/amd64"}
* Resource definition:
# Elastic YAML

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: faster
provisioner: kubernetes.io/gce-pd
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-ssd
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slower
provisioner: kubernetes.io/gce-pd
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-standard
---
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.4.0
  http:
    service:
      spec:
        type: LoadBalancer
  nodeSets:
    
  - name: zone-a-masters
    count: 1
    config:
      node.attr.attr_name: attr_value
      node.attr.zone: us-west2-a
      cluster.routing.allocation.awareness.attributes: zone
      node.master: true
      node.data: false
      node.ingest: false
      node.ml: false
      xpack.ml.enabled: true
      cluster.remote.connect: false
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms20g -Xmx20g
          resources:
            requests:
              memory: 40Gi
              cpu: 5
            limits:
              memory: 40Gi
              cpu: 7
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - us-west2-a
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: slower

  - name: zone-a-data
    count: 3
    config:
      node.attr.attr_name: attr_value
      node.attr.zone: us-west2-a
      cluster.routing.allocation.awareness.attributes: zone
      node.master: false
      node.data: true
      node.ingest: false
      node.ml: false
      xpack.ml.enabled: true
      cluster.remote.connect: false
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms20g -Xmx20g
          resources:
            requests:
              memory: 40Gi
              cpu: 5
            limits:
              memory: 40Gi
              cpu: 7
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - us-west2-a
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: faster
   

  - name: zone-b-masters
    count: 1
    config:
      node.attr.attr_name: attr_value
      node.attr.zone: us-west2-b
      cluster.routing.allocation.awareness.attributes: zone
      node.master: true
      node.data: false
      node.ingest: false
      node.ml: false
      xpack.ml.enabled: true
      cluster.remote.connect: false
    podTemplate:
       spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms20g -Xmx20g
          resources:
            requests:
              memory: 40Gi
              cpu: 5
            limits:
              memory: 40Gi
              cpu: 7
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - us-west2-b
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: slower

  - name: zone-b-data
    count: 3
    config:
      node.attr.attr_name: attr_value
      node.attr.zone: us-west2-b
      cluster.routing.allocation.awareness.attributes: zone
      node.master: false
      node.data: true
      node.ingest: false
      node.ml: false
      xpack.ml.enabled: true
      cluster.remote.connect: false
    podTemplate:
       spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms20g -Xmx20g
          resources:
            requests:
              memory: 40Gi
              cpu: 5
            limits:
              memory: 40Gi
              cpu: 7
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - us-west2-b
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: faster
        
  - name: zone-c-masters
    count: 1
    config:
      node.attr.attr_name: attr_value
      node.attr.zone: us-west2-c
      cluster.routing.allocation.awareness.attributes: zone
      node.master: true
      node.data: false
      node.ingest: false
      node.ml: false
      xpack.ml.enabled: true
      cluster.remote.connect: false
    podTemplate:
       spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms20g -Xmx20g
          resources:
            requests:
              memory: 40Gi
              cpu: 5
            limits:
              memory: 40Gi
              cpu: 7
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - us-west2-c
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: slower

  - name: zone-c-data
    count: 3
    config:
      node.attr.attr_name: attr_value
      node.attr.zone: us-west2-c
      cluster.routing.allocation.awareness.attributes: zone
      node.master: false
      node.data: true
      node.ingest: false
      node.ml: false
      xpack.ml.enabled: true
      cluster.remote.connect: false
    podTemplate:
       spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms20g -Xmx20g
          resources:
            requests:
              memory: 40Gi
              cpu: 5
            limits:
              memory: 40Gi
              cpu: 7
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - us-west2-c
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: faster
---

# Kibana YAML
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: quickstart-kibana
spec:
  version: 7.4.0
  count: 1
  elasticsearchRef:
    name: quickstart
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 2Gi
            cpu: 2
  http:
    service:
      spec:
        type: LoadBalancer
    tls:
      selfSignedCertificate:
        disabled: true

* Logs:

# Kibana error
No monitoring data found. Try setting the time filter to "Last 1 hour" or check if data is available for a different time period.

If data is in your cluster, your monitoring dashboards will show up here.

# Console GET /_cat/indices
green open .security-7            v0E3i6KrSqCexBMA2QFFDg 1 1 36 0 175.9kb 86.8kb
green open .kibana_task_manager_1 3VcO57hpT0asGMtgfWIidA 1 1  2 0  76.1kb 46.1kb
green open .kibana_1              28mjGCIcQUiDoDSRv4JKFw 1 1  8 0  60.3kb 31.8kb

# Console GET _cluster/settings
{
  "persistent" : {
    "xpack" : {
      "monitoring" : {
        "collection" : {
          "enabled" : "true"
        }
      }
    }
  },
  "transient" : {
    "cluster" : {
      "routing" : {
        "allocation" : {
          "exclude" : {
            "_name" : "none_excluded"
          }
        }
      }
    }
  }
}

# Console GET /_cluster/health?wait_for_status=yellow&timeout=50s
{
  "cluster_name" : "quickstart",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 12,
  "number_of_data_nodes" : 9,
  "active_primary_shards" : 3,
  "active_shards" : 6,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}

**Comment by charith-elastic** [comment] 2019-10-25 07:26
I think the issue is that you have no ingest nodes in your cluster. I managed to reproduce the issue by having a cluster without any ingest nodes. Then I updated the cluster to have some ingest nodes and the monitoring data became available again.

Closing this issue for now. Please re-open if adding ingest nodes does not resolve the issue.

**Closed by charith-elastic** 2019-10-25 07:26 UTC
