### ISSUE TITLE
Multiple secureSettings secrets does not work as intended

### ISSUE THREAD

**Issue by naemono** [elastic/cloud-on-k8s#5548] opened 2022-04-01 20:21 UTC
**What did you do?**

Created Kibana with this manifest

```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kb1
spec:
  version: 8.1.1
  count: 1
  elasticsearchRef:
    name: testing
  secureSettings:
  - secretName: kibana-secret-settings-encryption
  - secretName: kibana-secret-settings-decryption
```

With secrets
```
kubectl create secret generic kibana-secret-settings-encryption --from-literal=xpack.encryptedSavedObjects.encryptionKey=2rFwFGhZPNNKKYxUhh5AHgOJ1ECcHzOM -n default
kubectl create secret generic kibana-secret-settings-decryption --from-literal=xpack.encryptedSavedObjects.decryptionKey=2rFwFGhZPNNKKYxUhh5AHgOJ1ECcHzOM -n default
```

**What did you expect to see?**

Functioning Kibana with encryption/decryption keys set in the keystore.

**What did you see instead? Under which circumstances?**

Note the missing decryptionKey in the init container
```
❯ kc logs -l common.k8s.elastic.co/type=kibana -c elastic-internal-init-keystore
+ for filename in /mnt/elastic-internal/secure-settings/*
+ [[ -e /mnt/elastic-internal/secure-settings/xpack.encryptedSavedObjects.encryptionKey ]]
++ basename /mnt/elastic-internal/secure-settings/xpack.encryptedSavedObjects.encryptionKey
+ key=xpack.encryptedSavedObjects.encryptionKey
+ echo 'Adding xpack.encryptedSavedObjects.encryptionKey to the keystore.'
Adding xpack.encryptedSavedObjects.encryptionKey to the keystore.
+ /usr/share/kibana/bin/kibana-keystore add xpack.encryptedSavedObjects.encryptionKey --stdin
+ touch /usr/share/kibana/config/elastic-internal-init-keystore.ok
+ echo 'Keystore initialization successful.'
Keystore initialization successful.
```

And the failure of Kibana
```
kcubectl logs -n default kb1-kb-7b7b968845-sb9wm
[2022-04-01T20:17:56.753+00:00][FATAL][root] Error: [config validation of [xpack.encryptedSavedObjects].decryptionKey]: definition for this key is missing
    at ObjectType.validate (/usr/share/kibana/node_modules/@kbn/config-schema/target_node/types/type.js:95:13)
    at ConfigService.validateAtPath (/usr/share/kibana/node_modules/@kbn/config/target_node/config_service.js:228:19)
    at MapSubscriber.project (/usr/share/kibana/node_modules/@kbn/config/target_node/config_service.js:236:169)
```

**Environment**

* ECK version:

	2.1.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ?
	* Cloud: GKE / EKS / AKS ?
	* Kubernetes distribution: Openshift / Rancher / PKS ?
	
	for each of them please give us the version you are using
```
❯ kc version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6-gke.300", GitCommit:"df413ee6225aa3fc539e18ca3464a48d723bd3ea", GitTreeState:"clean", BuildDate:"2022-01-24T09:29:08Z", GoVersion:"go1.16.12b7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by pebrc** [comment] 2022-04-05 18:39
@naemono I cannot reproduce the issue you are describing here. 

Your example does not work because there is no `xpack.encryptedSavedObjects.decryptionKey` setting in Kibana. 

The only `decryptionKey` setting in Kibana is for key rotation purposes and it is an array of previously used encryption keys so saved objects written with the old key can still be read after keys have been rotated. 

If I fix your example to use two valid Kibana settings, I can configure Kibana just fine no matter how many secrets are used to  specify the keystore settings: 

```
kubectl create secret generic kibana-secret-settings-encryption --from-literal=xpack.encryptedSavedObjects.encryptionKey=2rFwFGhZPNNKKYxUhh5AHgOJ1ECcHzOM 
kubectl create secret generic kibana-secret-settings-decryption --from-literal=xpack.encryptedSavedObjects.keyRotation.decryptionOnlyKeys.0=qpz2r7NoipfmmUHNPxVguw1Qy4niFHmfNtYB0vqZTH1NYz8E6dQhi7NdfzX0EgIl
```
Note: the encryption and decryption key must not be the same

with this secret setup and your Kibana example everything works as advertised. I am tempted to close this issue. Please reopen if I missed something!

**Closed by pebrc** 2022-04-05 18:39 UTC
Labels: >bug
