### ISSUE TITLE
Provide more details on "Managing compute resources"

### ISSUE THREAD

**Issue by alaudazzi** [elastic/cloud-on-k8s#2601] opened 2020-02-24 12:12 UTC
More detailed information is required on this page:
https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-managing-compute-resources.html 

- In the configuration files, explain where resource requests should be applied.
- The resource configuration examples lack context: what apiVersion and kind of resource do they apply to?

Including the entire yaml manifest in every example might help.

**Comment by pebrc** [comment] 2020-02-24 12:48
Duplicate of #2557

**Comment by alaudazzi** [comment] 2020-03-04 08:39
We might add the following lines to each doc sample:
For Elasticsearch-related  docs:
```
apiVersion: elasticsearch.k8s.elastic.co/{eck_crd_version}
kind: Elasticsearch
metadata:
  name: quickstart
```
For Kibana-related  docs:
```
apiVersion: elasticsearch.k8s.elastic.co/{eck_crd_version}
kind: Kibana
metadata:
  name: quickstart
```

For APM-related  docs:
```
apiVersion: elasticsearch.k8s.elastic.co/{eck_crd_version}
kind: ApmServer
metadata:
  name: quickstart
```

**Comment by alaudazzi** [comment] 2020-03-04 14:57
After discussion with @charith-elastic:
We add the yaml manifest only to the doc samples in [Manage compute resources](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-managing-compute-resources.html).

**Closed** 2020-03-05 09:08 UTC
Labels: >docs
