### ISSUE TITLE
Kubernetes Elastic Operator Image Pull Forbidden

### ISSUE THREAD

**Issue by EricNexus** [elastic/cloud-on-k8s#5567] opened 2022-04-11 09:43 UTC
Hello, I have problem with Elastic Operator image.
Following official quickstart guide run in problem with image pull. 
Whole message error: "Failed to pull image "docker.elastic.co/eck/eck-operator:2.1.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.elastic.co/eck/eck-operator:2.1.0": failed to copy: httpReadSeeker: failed open: unexpected status code https://docker.elastic.co/v2/eck/eck-operator/blobs/sha256:33bee0e5ef113275240a798f7e2707a86442a01b313c62ed448ec859989e5bf7: 403 Forbidden"
Although, on another kubernetes cluster same "kubectl apply -f https://download.elastic.co/downloads/eck/2.1.0/operator.yaml" works as expected. 
Where should I look for cause of this problem?

**Comment by barkbay** [comment] 2022-04-12 08:10
I cannot reproduce, maybe you hit a small registry disruption, however it seems to be working as expected now.
I'm closing because I think this is more an infra issue than something related to the ECK operator itself. Feel free to reopen if needed.

**Closed by barkbay** 2022-04-12 08:10 UTC
Labels: triage

**Comment by EricNexus** [comment] 2022-04-14 05:47
Is it possible that for russian ips image download forbidden?
Resolve this by downloading image from home server and export it to problem server
![Screenshot 2022-04-14 11 14 03](https://user-images.githubusercontent.com/60914006/163321882-d0df04a3-2ad1-44e8-bed5-c91db8b252a6.png)
