### ISSUE TITLE
eck/eck-operator fips and ubi

### ISSUE THREAD

**Issue by ke5C2Fin** [elastic/cloud-on-k8s#8204] opened 2024-11-14 21:06 UTC
Default image is `eck/eck-operator:2.15.0`.
https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s_installation.html#k8s_fips_compliant_installation_using_helm
This document says to set `image.repository=docker.elastic.co/eck/eck-operator-fips`, which gives us this image `eck/eck-operator-fips:2.15.0`.
If we do not do that, but we set `config.ubiOnly=true`, we get this image `eck/eck-operator-ubi:2.15.0`.
However, if we set both fips and ubi we get this image `eck/eck-operator-fips-ubi:2.15.0`, which doesn't exist because the actual image is `eck/eck-operator-ubi-fips:2.15.0`.

**Comment by thbkrkr** [comment] 2024-11-15 11:37
Thank you for reporting this. The issue is indeed a bug in how the Helm chart constructs the image name when it contains `-fips` and `config.ubiOnly` is enabled. We’ll work on resolving this. In the meantime, I think you can use the following workaround:

```sh
helm install elastic-operator elastic/eck-operator \
  -n elastic-system --create-namespace \
  --set=image.repository=docker.elastic.co/eck/eck-operator-ubi-fips \
  --set=config.containerSuffix=-ubi
```

**Closed** 2024-11-28 13:56 UTC
Labels: >bug, v2.16.0 (next)
