### ISSUE TITLE
Sometimes changes of resources won't propagate to related statefulset

### ISSUE THREAD

**Issue by bluven** [elastic/cloud-on-k8s#2854] opened 2020-04-10 02:03 UTC
## Bug Report
**What did you do?**
I gived requests a biggger value than limits of elasticsearch container on one nodeset, then found the related statefulset complaint:
```
 Warning  FailedCreate      1s (x16 over 2m26s)  statefulset-controller  create Pod quickstart-es-default-2 in StatefulSet quickstart-es-default failed error: Pod "quickstart-es-default-2" is invalid: spec.containers[0].resources.requests: Invalid value: "2": must be less than or equal to cpu limit",
```
then I set requests to a smaller value that limits

**What did you expect to see?**
The related statefulset should have the same resources as the nodeset

**What did you see instead? Under which circumstances?**

The related statefulset was stucked on the wrong resources setting

**Environment**

* ECK version:

	1.0.1

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ? yes
	* Cloud: GKE / EKS / AKS ? no
	* Kubernetes distribution: Openshift / Rancher / PKS ? just Kubernetes 1.17.0
	
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

```

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.6.0
  image: registry.bluven.me:5000/bocloud/elasticsearch:7.6.0
  updateStrategy:
    changeBudget:
      maxSurge: 1
      maxUnavailable: 1
  nodeSets:
  - name: default
    count: 3
    config:
      node.master: true
      node.data: true
      node.ingest: false
      node.store.allow_mmap: false
      transport.compress: true
---

```

* Logs:
```
Name:         quickstart
Namespace:    default
Labels:       <none>
Annotations:  common.k8s.elastic.co/controller-version: 1.0.1
              elasticsearch.k8s.elastic.co/cluster-uuid: 1yRU-j4qRVC0-SIhEDNfsg
              kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"elasticsearch.k8s.elastic.co/v1","kind":"Elasticsearch","metadata":{"annotations":{},"name":"quickstart","namespace":"defau...
API Version:  elasticsearch.k8s.elastic.co/v1
Kind:         Elasticsearch
Metadata:
  Creation Timestamp:  2020-04-09T09:09:05Z
  Generation:          7
  Resource Version:    18558817
  Self Link:           /apis/elasticsearch.k8s.elastic.co/v1/namespaces/default/elasticsearches/quickstart
  UID:                 e4921a41-291c-4c70-af84-f789b3e1eb9e
Spec:
  Http:
    Service:
      Metadata:
        Creation Timestamp:  <nil>
      Spec:
    Tls:
      Certificate:
  Image:  registry.bluven.me:5000/bocloud/elasticsearch:7.6.0
  Node Sets:
    Config:
      node.data:              true
      node.ingest:            true
      node.master:            true
      node.store.allow_mmap:  false
      transport.compress:     true
    Count:                    3
    Name:                     default
    Pod Template:
      Metadata:
      Spec:
        Containers:
          Name:  elasticsearch
          Resources:
            Limits:
              Cpu:     1
              Memory:  4Gi
            Requests:
              Cpu:     1
              Memory:  1Gi
  Update Strategy:
    Change Budget:
  Version:  7.6.0
Status:
  Available Nodes:  2
  Health:           green
  Phase:            ApplyingChanges
Events:             <none>

---------------------------------------------

Name:               quickstart-es-default
Namespace:          default
CreationTimestamp:  Thu, 09 Apr 2020 17:09:06 +0800
Selector:           common.k8s.elastic.co/type=elasticsearch,elasticsearch.k8s.elastic.co/cluster-name=quickstart,elasticsearch.k8s.elastic.co/statefulset-name=quickstart-es-default
Labels:             common.k8s.elastic.co/template-hash=2713753207
                    common.k8s.elastic.co/type=elasticsearch
                    elasticsearch.k8s.elastic.co/cluster-name=quickstart
                    elasticsearch.k8s.elastic.co/statefulset-name=quickstart-es-default
Annotations:        <none>
Replicas:           3 desired | 3 total
Update Strategy:    OnDelete
Pods Status:        2 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  common.k8s.elastic.co/type=elasticsearch
           elasticsearch.k8s.elastic.co/cluster-name=quickstart
           elasticsearch.k8s.elastic.co/config-hash=4133117001
           elasticsearch.k8s.elastic.co/http-scheme=https
           elasticsearch.k8s.elastic.co/node-data=true
           elasticsearch.k8s.elastic.co/node-ingest=true
           elasticsearch.k8s.elastic.co/node-master=true
           elasticsearch.k8s.elastic.co/node-ml=true
           elasticsearch.k8s.elastic.co/statefulset-name=quickstart-es-default
           elasticsearch.k8s.elastic.co/version=7.6.0
  Init Containers:
   elastic-internal-init-filesystem:
    Image:      registry.bluven.me:5000/bocloud/elasticsearch:7.6.0
    Port:       <none>
    Host Port:  <none>
    Command:
      bash
      -c
      /mnt/elastic-internal/scripts/prepare-fs.sh
    Limits:
      cpu:     100m
      memory:  50Mi
    Requests:
      cpu:     100m
      memory:  50Mi
    Environment:
      POD_IP:     (v1:status.podIP)
      POD_NAME:   (v1:metadata.name)
      POD_IP:     (v1:status.podIP)
      POD_NAME:   (v1:metadata.name)
    Mounts:
      /mnt/elastic-internal/downward-api from downward-api (ro)
      /mnt/elastic-internal/elasticsearch-bin-local from elastic-internal-elasticsearch-bin-local (rw)
      /mnt/elastic-internal/elasticsearch-config from elastic-internal-elasticsearch-config (ro)
      /mnt/elastic-internal/elasticsearch-config-local from elastic-internal-elasticsearch-config-local (rw)
      /mnt/elastic-internal/elasticsearch-plugins-local from elastic-internal-elasticsearch-plugins-local (rw)
      /mnt/elastic-internal/probe-user from elastic-internal-probe-user (ro)
      /mnt/elastic-internal/scripts from elastic-internal-scripts (ro)
      /mnt/elastic-internal/transport-certificates from elastic-internal-transport-certificates (ro)
      /mnt/elastic-internal/unicast-hosts from elastic-internal-unicast-hosts (ro)
      /mnt/elastic-internal/xpack-file-realm from elastic-internal-xpack-file-realm (ro)
      /usr/share/elasticsearch/config/http-certs from elastic-internal-http-certificates (ro)
      /usr/share/elasticsearch/data from elasticsearch-data (rw)
      /usr/share/elasticsearch/logs from elasticsearch-logs (rw)
  Containers:
   elasticsearch:
    Image:       registry.bluven.me:5000/bocloud/elasticsearch:7.6.0
    Ports:       9200/TCP, 9300/TCP
    Host Ports:  0/TCP, 0/TCP
    Limits:
      cpu:     1
      memory:  4Gi
    Requests:
      cpu:      2
      memory:   4Gi
    Readiness:  exec [bash -c /mnt/elastic-internal/scripts/readiness-probe-script.sh] delay=10s timeout=5s period=5s #success=1 #failure=3
    Environment:
      HEADLESS_SERVICE_NAME:     quickstart-es-default
      NSS_SDB_USE_CACHE:         no
      POD_IP:                     (v1:status.podIP)
      POD_NAME:                   (v1:metadata.name)
      PROBE_PASSWORD_PATH:       /mnt/elastic-internal/probe-user/elastic-internal-probe
      PROBE_USERNAME:            elastic-internal-probe
      READINESS_PROBE_PROTOCOL:  https
    Mounts:
      /mnt/elastic-internal/downward-api from downward-api (ro)
      /mnt/elastic-internal/elasticsearch-config from elastic-internal-elasticsearch-config (ro)
      /mnt/elastic-internal/probe-user from elastic-internal-probe-user (ro)
      /mnt/elastic-internal/scripts from elastic-internal-scripts (ro)
      /mnt/elastic-internal/unicast-hosts from elastic-internal-unicast-hosts (ro)
      /mnt/elastic-internal/xpack-file-realm from elastic-internal-xpack-file-realm (ro)
      /usr/share/elasticsearch/bin from elastic-internal-elasticsearch-bin-local (rw)
      /usr/share/elasticsearch/config from elastic-internal-elasticsearch-config-local (rw)
      /usr/share/elasticsearch/config/http-certs from elastic-internal-http-certificates (ro)
      /usr/share/elasticsearch/config/transport-certs from elastic-internal-transport-certificates (ro)
      /usr/share/elasticsearch/data from elasticsearch-data (rw)
      /usr/share/elasticsearch/logs from elasticsearch-logs (rw)
      /usr/share/elasticsearch/plugins from elastic-internal-elasticsearch-plugins-local (rw)
  Volumes:
   downward-api:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.labels -> labels
   elastic-internal-elasticsearch-bin-local:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
   elastic-internal-elasticsearch-config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  quickstart-es-default-es-config
    Optional:    false
   elastic-internal-elasticsearch-config-local:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
   elastic-internal-elasticsearch-plugins-local:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
   elastic-internal-http-certificates:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  quickstart-es-http-certs-internal
    Optional:    false
   elastic-internal-probe-user:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  quickstart-es-internal-users
    Optional:    false
   elastic-internal-scripts:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      quickstart-es-scripts
    Optional:  false
   elastic-internal-transport-certificates:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  quickstart-es-transport-certificates
    Optional:    false
   elastic-internal-unicast-hosts:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      quickstart-es-unicast-hosts
    Optional:  false
   elastic-internal-xpack-file-realm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  quickstart-es-xpack-file-realm
    Optional:    false
   elasticsearch-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  claim-name-placeholder
    ReadOnly:   false
   elasticsearch-logs:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
Volume Claims:
  Name:          elasticsearch-data
  StorageClass:  
  Labels:        <none>
  Annotations:   <none>
  Capacity:      1Gi
  Access Modes:  [ReadWriteOnce]
Events:
  Type     Reason            Age                 From                    Message
  ----     ------            ----                ----                    -------
  Normal   SuccessfulCreate  47m (x4 over 16h)   statefulset-controller  create Pod quickstart-es-default-1 in StatefulSet quickstart-es-default successful
  Normal   SuccessfulCreate  45m (x3 over 16h)   statefulset-controller  create Pod quickstart-es-default-2 in StatefulSet quickstart-es-default successful
  Normal   SuccessfulCreate  43m (x2 over 16h)   statefulset-controller  create Pod quickstart-es-default-0 in StatefulSet quickstart-es-default successful
  Warning  FailedCreate      10s (x19 over 21m)  statefulset-controller  create Pod quickstart-es-default-2 in StatefulSet quickstart-es-default failed error: Pod "quickstart-es-default-2" is invalid: spec.containers[0].resources.requests: Invalid value: "2": must be less than or equal to cpu limit

----


```

**Comment by sebgl** [comment] 2020-04-10 09:12
Hi @bluven,

Can you post the output of `kubecgl get pod quickstart-es-default-2 -o json`? I'm curious about the state of that Pod. It should normally be eventually rolled out.

As a side note: you  probably want to set the same memory requests and limits, and make sure you adapt the JVM memory accordingly. See [this doc](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-managing-compute-resources.html#k8s-compute-resources-elasticsearch).

**Comment by sebgl** [comment] 2020-04-10 09:20
There is a bug indeed, I managed to reproduce:

- deploy a cluster with correct cpu req and limits
- apply a modification with a cpu req higher than limit
- see how the Pod does not get created because of the resource error
- at this point ECK waits forever until the pod that is supposed to be created gets created
- apply the manifest again with the fixed cpu requests
- ECK stays stuck waiting for the Pod to be created before it can move on with updating the StatefulSet

**Comment by sebgl** [comment] 2020-04-10 09:23
This is actually this bug: https://github.com/elastic/cloud-on-k8s/issues/2266.
@bluven I'll close this issue and report that use case in the other one.

In the meantime, as a workaround, you can edit the existing StatefulSet (`kubectl edit quickstart-es-default `) to fix the cpu requests. This should unlock the situation.

**Closed by sebgl** 2020-04-10 09:23 UTC
Labels: triage
