### ISSUE TITLE
CRDs doesn't follow helm's guidelines about `crd` directory

### ISSUE THREAD

**Issue by szymonrychu** [elastic/cloud-on-k8s#4856] opened 2021-09-21 08:02 UTC
In order to deploy eck helm chart along with a chart that would use it, helm provides a guide, that describes, that it's necessary to pack CRDs to `crd` directory (separate from `templates`).

Current charts doesn't support that, which makes it impossible to deploy a ES cluster and use it in one helm run (even if it's supported by the tool).

In my opinion it's a misuse of the deploying tool supported in the official documentation, which qualifies as a bug.

Moreover it makes it impossible to use chart according to parent best-practices, or include it in umbrella helm-charts, or helmfile.

**Comment by szymonrychu** [comment] 2021-09-21 08:02
link to guide: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/

**Comment by barkbay** [comment] 2021-09-21 08:10
It seems to be a duplicate of https://github.com/elastic/cloud-on-k8s/issues/4222#issuecomment-775770168 and I think https://github.com/helm/helm/issues/5871 is still not solved.

**Comment by szymonrychu** [comment] 2021-09-21 08:27
As far as I can see issue mentioned by you is closed, therefore it seems resolved.

Also official documentation is also updated and the `crd` dir is advertised as something that's working (but has some limitations).

Therefore convention exists and eck chart doesn't follows it, which blocks me from laveraging helmfile for 1shot deployments of the environments I work on. 
The only workaround involving helm I can think of now is to do locally what should be done in upstream, therefore I've created this Issue.

**Comment by barkbay** [comment] 2021-09-21 12:52
> As far as I can see issue mentioned by you is closed, therefore it seems resolved

I think the aforementioned Helm issue has been automatically closed because of inactivity: https://github.com/helm/helm/issues/5871#issuecomment-731657888, without any proper solution.
IIUC the concerns raised in https://github.com/elastic/cloud-on-k8s/issues/4222#issuecomment-775770168 seem to be still relevant.

**Comment by barkbay** [comment] 2021-10-12 07:21
> IIUC the concerns raised in #4222 (comment) seem to be still relevant.

Closing this issue, please let me know if you think it is not the case.

**Closed by barkbay** 2021-10-12 07:21 UTC
Labels: triage
