### ISSUE TITLE
CRDs rejected by Kubernetes 1.16 due to not having spec.validation.openAPIV3Schema.type

### ISSUE THREAD

**Issue by charith-elastic** [elastic/cloud-on-k8s#2559] opened 2020-02-13 09:45 UTC
We remove the `spec.validation.openAPIV3Schema.type` field via a [Kustomize patch](https://github.com/elastic/cloud-on-k8s/commit/e16b65bbd533e427d73ec2f7c8bb9d885aa7f5ea#diff-7b9c2d4fe0773b439a6bc14df50beac4) to support Kubernetes 1.11. However, this field seems to be mandatory in Kubernetes 1.16.

```
kubectl apply -f config/crds/all-crds.yaml
Error from server (Invalid): error when creating "config/crds/all-crds.yaml": CustomResourceDefinition.apiextensions.k8s.io "apmservers.apm.k8s.elastic.co" is invalid: spec.validation.openAPIV3Schema.type: Required value: must not be empty at the root
Error from server (Invalid): error when creating "config/crds/all-crds.yaml": CustomResourceDefinition.apiextensions.k8s.io "elasticsearches.elasticsearch.k8s.elastic.co" is invalid: spec.validation.openAPIV3Schema.type: Required value: must not be empty at the root
Error from server (Invalid): error when creating "config/crds/all-crds.yaml": CustomResourceDefinition.apiextensions.k8s.io "kibanas.kibana.k8s.elastic.co" is invalid: spec.validation.openAPIV3Schema.type: Required value: must not be empty at the root
```

**Comment by sebgl** [comment] 2020-02-13 09:51
Meh :(

If we cannot find an easy way around it I guess we'll have to generate 2 versions of the CRDs: one for K8s < 1.16 and one for K8s 1.16+.

The second one would eventually allow us to do [CRD versioning the right way](https://github.com/elastic/cloud-on-k8s/issues/479#issuecomment-566089862) and use [structural schemas](https://kubernetes.io/blog/2019/06/20/crd-structural-schema/).

**Comment by anyasabo** [comment] 2020-02-13 14:48
I can't reproduce this with 1.0.1:

```
08:41 $ minikube start --kubernetes-version=1.16.7
🎉  minikube 1.7.2 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.7.2
💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'

🙄  minikube v1.6.2 on Darwin 10.15.3
✨  Selecting 'hyperkit' driver from existing profile (alternates: [virtualbox])
👍  Kubernetes 1.17.0 is now available. If you would like to upgrade, specify: --kubernetes-version=1.17.0
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing hyperkit VM for "minikube" ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.16.7 on Docker '19.03.5' ...
💾  Downloading kubelet v1.16.7
💾  Downloading kubeadm v1.16.7
🚜  Pulling images ...
🚀  Launching Kubernetes ... 
🏄  Done! kubectl is now configured to use "minikube"
✔ ~/dev/go/src/github.com/elastic/cloud-on-k8s [shellcheck L|✔] 
08:43 $ kubectl apply -f https://download.elastic.co/downloads/eck/1.0.1/all-in-one.yaml
customresourcedefinition.apiextensions.k8s.io/apmservers.apm.k8s.elastic.co created
customresourcedefinition.apiextensions.k8s.io/elasticsearches.elasticsearch.k8s.elastic.co created
customresourcedefinition.apiextensions.k8s.io/kibanas.kibana.k8s.elastic.co created
clusterrole.rbac.authorization.k8s.io/elastic-operator created
clusterrolebinding.rbac.authorization.k8s.io/elastic-operator created
namespace/elastic-system created
statefulset.apps/elastic-operator created
serviceaccount/elastic-operator created
validatingwebhookconfiguration.admissionregistration.k8s.io/elastic-webhook.k8s.elastic.co created
service/elastic-webhook-server created
secret/elastic-webhook-server-cert created
```

I did run into this with bumping our deps to k8s 1.17 as part of https://github.com/elastic/cloud-on-k8s/pull/2497 but removing the extra fields seems to do the trick. I can repro this on master (since another PR bumped our k8s deps in the meantime) + k8s 1.16, but not in that PR's branch.

**Comment by anyasabo** [comment] 2020-03-03 15:59
Fixed via https://github.com/elastic/cloud-on-k8s/pull/2497

**Closed by anyasabo** 2020-03-03 15:59 UTC
Labels: >bug
