### ISSUE TITLE
Kibana cannot resolve any internal DNS names

### ISSUE THREAD

**Issue by paddatrapper** [elastic/cloud-on-k8s#5313] opened 2022-02-01 11:43 UTC
## Bug Report
**What did you do?**

Running eck version 1.9.1, deploying ElasticSearch and Kibana with version 7.15.2. We are unable to test using 7.16, as there are no journalbeat docker images for any 7.16.x releases. ES and Kibana named `logs` in the `eck` namespace.

**What did you expect to see?**

Kibana to resolve the ES URL correctly.

**What did you see instead? Under which circumstances?**
ElasticSearch deploys correctly, however Kibana cannot resolve any internal DNS entries (for example `logs-es-http.eck.svc`). Downgrading to 7.10.2 causes the DNS to resolve correctly.

**Environment**

* ECK version:

	1.9.1

* Kubernetes information:

- AWS EKS running Kubernetes v1.21

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"archive", BuildDate:"2021-06-13T07:08:18Z", GoVersion:"go1.15.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by thbkrkr** [comment] 2022-02-01 14:13
> We are unable to test using 7.16, as there are no journalbeat docker images for any 7.16.x releases.

Journalbeat has been removed and is now released as a [Filebeat input](https://www.elastic.co/guide/en/beats/filebeat/7.16/filebeat-input-journald.html) (https://github.com/elastic/beats/pull/29131).s 

> Kibana cannot resolve any internal DNS entries (for example logs-es-http.eck.svc). Downgrading to 7.10.2 causes the DNS to resolve correctly.

It's very surprising. I'm tempted to think that the problem comes from the infrastructure (EKS). ECK is well tested on EKS.

Could you share the YAML manifest used to deploy ES and Kibana?
Did you test all minor versions between 7.15.2 and 7.10.2?
Did you try to upgrade the `7.10.2` cluster in `7.15.2`?
Are you using some special network configuration like private subnets?

**Comment by brsolomon-deloitte** [comment] 2022-02-15 21:43
We use Elastic stack 7.16 and EKS 1.21 and do not see this issue. Not sure why it would matter if subnet is private/public. it would seemingly be a kube coredns issue.

@paddatrapper can you elaborate on where exactly the dns resolution is failing?

It could be either (1) coredns issues or (2) for whatever reason the request is being routed over the internet rather than cluster-local. But neither of those is apparent from the info above.

**Comment by paddatrapper** [comment] 2022-02-16 07:06
> It could be either (1) coredns issues or (2) for whatever reason the request is being routed over the internet rather than cluster-local. But neither of those is apparent from the info above.

It isn't coredns because the Kibana 7.16 pod is the only pod having issues. Downgrading without any changes to the rest of the cluster solves the issue and any other pod I test with has no issues connecting or resolving internal domains. I can ping the DNS server from the Kibana pod. I can't do much more debugging than that due to it being an unprivileged pod, so I can't install dnsutils for better tools. `curl` reports unable to resolve host from within that pod. The `/etc/resolve.conf` looks to be correct and matches other pods in the cluster

**Comment by barkbay** [comment] 2022-02-16 12:02
> curl reports unable to resolve host from within that pod. The /etc/resolve.conf looks to be correct and matches other pods in the cluster

To double check what is happening at the CoreDNS level could you try the following:

1. Edit the coredns config: `kubectl -n kube-system edit configmap coredns`
2. Enable CoreDNS logging:

```yaml
kind: ConfigMap
apiVersion: v1
data:
  Corefile: |
    .:53 {
        log    # Enabling CoreDNS Logging
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
```
3. Delete the CoreDNS Pods to force a reload: `kubectl delete pods -n kube-system --selector 'k8s-app=kube-dns'`
4. Get CoreDNS logs `kubectl logs --follow -n kube-system --selector 'k8s-app=kube-dns'`
5. Trigger a resolution, using `curl` for example, from both the Kibana Pod and from another one.
6. Compare how the name is resolved in both cases. 

Thanks

**Comment by paddatrapper** [comment] 2022-02-16 12:06
Done that, the other pods reach the cubedns pod, while Kibana does not. I.e. There are resolution logs from other pods, but none from the Kibana pods

**Comment by barkbay** [comment] 2022-02-16 12:31
> There are resolution logs from other pods

Are they on the same K8S node ?

**Comment by barkbay** [comment] 2022-02-16 12:42
Could you also share the uncommented lines in `/etc/nsswitch.conf` ?

**Comment by barkbay** [comment] 2022-02-16 12:53
>  I can't do much more debugging than that due to it being an unprivileged pod, so I can't install dnsutils for better tools

You can run a container with some DNS tooling in the Kibana Pod. Assuming the problem is at the Pod level you might still hit the same problem:

```yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: logs
  namespace: eck
spec:
  version: 7.15.2
  count: 1
  podTemplate:
    spec:
      containers:
        - name: dnsutils
          image: k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.3
          command:
            - sleep
            - "3600"
          imagePullPolicy: IfNotPresent
  elasticsearchRef:
    name: logs
```

Maybe something like `dig +trace logs-es-http.eck.svc` could be then interesting.

**Comment by naemono** [comment] 2022-02-16 13:54
@paddatrapper 

Could you please share your coredns configuration?

```
kubectl -n kube-system get configmap coredns -o yaml
```

Are there any network policies in play that may block traffic between namespaces (eck -> kube-system for example)

```
kubectl get netpol -A
```

Would [Istio](https://istio.io/) be in play here?

Are there any mutating webhooks that are changing deployments/pods?

```
kubectl get MutatingWebhookConfiguration
```

Could you share the logs of the Kibana pod during failure please?

Also, could you share the Kibana deployment that is laid down by the operator?

```
kubectl get deployment -n eck -l common.k8s.elastic.co/type=kibana -o yaml
```

**Comment by barkbay** [comment] 2022-03-16 06:43
Closing due to inactivity. Feel free to reopen if needed.

**Closed by barkbay** 2022-03-16 06:43 UTC
Labels: triage
