### ISSUE TITLE
Document how/when to configure setVmMaxMapCount

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#970] opened 2019-05-31 09:18 UTC
It defaults to `true` and causes us to use a privileged init container to set this according to https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html.

If this is configured on the host level instead, the privileged container can be skipped, which is preferable from a general security standpoint.

**Comment by thbkrkr** [comment] 2019-07-15 14:36
Duplicate of #1031.

**Closed by thbkrkr** 2019-07-15 14:36 UTC
Labels: >docs
