### ISSUE TITLE
How to recreate xpack.fleet.agentPolicies ?

### ISSUE THREAD

**Issue by azhurbilo** [elastic/cloud-on-k8s#7135] opened 2023-08-30 16:07 UTC
## Proposal

**Use case. Why is this important?**

I have to recreate agentPolicies with new "namespace" as new value of namespace was applied in k8s but in kibana UI I see still old value and I didn't find how to do it.

## Bug Report
**What did you do?**

```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
spec:
  ...
    xpack.fleet.agentPolicies
      - name: Fleet Server on ECK policy
         id: eck-fleet-server
```

After manual deletion of policies and restart of fleet/kibana pods, nothing happened -> policies were not recreated

**What did you expect to see?**

 policies automatically recreated (synced) based on current kibana config

**What did you see instead? Under which circumstances?**

policies were not recreated.

as workaround I change policy ID in Kibana and Agent k8s resources and after apply it helps to generate new tokens with new policies

```
- name: Fleet Server on ECK policy
   id: eck-fleet-server ---> changed to "eck-fleet-server-policy"
```

**Environment**

* ECK version:

	2.9.0

* Kubernetes information:

	* Cloud: GKE

**Comment by pebrc** [comment] 2024-12-31 13:45
Did you have  `is_managed: true` set on the policy? 

https://github.com/elastic/cloud-on-k8s/pull/8125 added this recently to our example manifests as we realised that policies that are not marked as managed are otherwise not updated. 

I am closing this as a duplicate of https://github.com/elastic/cloud-on-k8s/issues/7290 (please reopen if your case is different)

**Closed by pebrc** 2024-12-31 13:45 UTC
Labels: >bug
