### ISSUE TITLE
Reference docs for Kibana deployment

### ISSUE THREAD

**Issue by weeco** [elastic/cloud-on-k8s#2063] opened 2019-10-25 11:54 UTC
Hey, I am looking for reference docs to deploy Kibana. I have only found https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-kibana.html .

For instance I am currently trying to disable the need of a user/pass authentication as I use an OAuth proxy in front of it. Therefore my resource looks like this:

```yaml
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: logging # -kb is suffixed for kibana pods/deployments
  namespace: elastic-system
spec:
  version: 7.4.0
  count: 2
  config:
    xpack.security.enabled: false
    xpack.apm.enabled: false
  elasticsearchRef:
    name: logging
    namespace: elastic-system
  http:
    tls:
      selfSignedCertificate:
        disabled: true
```

For some reason I end up with a basic auth, which btw apparently also causes the readiness probe to fail. More documentation about the Kibana resource is highly appreciated, and if possible someone can tell me how I can disable the user/pass authentication.

**Comment by charith-elastic** [comment] 2019-10-25 13:22
Hi, setting `xpack.security.enabled` to `false` is not recommended as it prevents Kibana from being able to authenticate itself to Elasticsearch. I suspect this is why the readiness probe is failing as well. https://www.elastic.co/guide/en/kibana/current/security-settings-kb.html

You are describing a fairly specialized scenario that we haven't tested with ECK so it is difficult to provide any specific instructions.  As far as I am aware, we do not have any special configuration options in the Kibana resource that would affect this use case. Perhaps you will find https://www.elastic.co/blog/user-impersonation-with-x-pack-integrating-third-party-auth-with-kibana helpful to figure out the settings you need to configure. It would be better to post this question in the discussion forum at https://discuss.elastic.co/c/eck to get a wider audience as well.

Regarding documentation, we are already working on providing API reference documentation in the next release.

**Comment by charith-elastic** [comment] 2019-10-28 10:09
API reference documentation is now available in the master branch: https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-api-reference.html

I am closing this issue since it's not a bug in the operator. Please feel free to re-open if you find anything that suggests otherwise.

**Closed by charith-elastic** 2019-10-28 10:09 UTC

**Comment by wangycc** [comment] 2019-10-29 09:50
+1
